var sunburst_data = [{
    'id': '0.0',
    'parent': '',
    'name': '全上海'
            }, {
    'id': '1.1',
    'parent': '0.0',
    'name': '卢湾'
}, {
    'id': '1.2',
    'parent': '0.0',
    'name': '嘉定'
}, {
    'id': '1.3',
    'parent': '0.0',
    'name': '宝山'
}, {
    'id': '1.4',
    'parent': '0.0',
    'name': '徐汇'
}, {
    'id': '1.5',
    'parent': '0.0',
    'name': '普陀'
}, {
    'id': '1.6',
    'parent': '0.0',
    'name': '杨浦'
}, {
    'id': '1.7',
    'parent': '0.0',
    'name': '松江'
}, {
    'id': '1.8',
    'parent': '0.0',
    'name': '浦东'
}, {
    'id': '1.9',
    'parent': '0.0',
    'name': '虹口'
}, {
    'id': '1.10',
    'parent': '0.0',
    'name': '金山'
}, {
    'id': '1.11',
    'parent': '0.0',
    'name': '长宁'
}, {
    'id': '1.12',
    'parent': '0.0',
    'name': '闵行'
}, {
    'id': '1.13',
    'parent': '0.0',
    'name': '闸北'
}, {
    'id': '1.14',
    'parent': '0.0',
    'name': '青浦'
}, {
    'id': '1.15',
    'parent': '0.0',
    'name': '静安'
}, {
    'id': '1.16',
    'parent': '0.0',
    'name': '黄浦'
}, {
    'id': '2.1',
    'parent': '1.1',
    'name': ' 复兴公园 '
}, {
    'id': '2.2',
    'parent': '1.1',
    'name': ' 打浦桥 '
}, {
    'id': '2.3',
    'parent': '1.1',
    'name': ' 淮海中路 '
}, {
    'id': '2.4',
    'parent': '1.1',
    'name': ' 淮海路/新天地 '
}, {
    'id': '2.5',
    'parent': '1.2',
    'name': ' 南翔 '
}, {
    'id': '2.6',
    'parent': '1.2',
    'name': ' 嘉定城区 '
}, {
    'id': '2.7',
    'parent': '1.2',
    'name': ' 安亭 '
}, {
    'id': '2.8',
    'parent': '1.2',
    'name': ' 江桥 '
}, {
    'id': '2.9',
    'parent': '1.3',
    'name': ' 上海大学 '
}, {
    'id': '2.10',
    'parent': '1.3',
    'name': ' 共富 '
}, {
    'id': '2.11',
    'parent': '1.3',
    'name': ' 共康 '
}, {
    'id': '2.12',
    'parent': '1.3',
    'name': ' 吴淞 '
}, {
    'id': '2.13',
    'parent': '1.3',
    'name': ' 大华 '
}, {
    'id': '2.14',
    'parent': '1.3',
    'name': ' 大场镇 '
}, {
    'id': '2.15',
    'parent': '1.3',
    'name': ' 杨行 '
}, {
    'id': '2.16',
    'parent': '1.3',
    'name': ' 淞南高境 '
}, {
    'id': '2.17',
    'parent': '1.3',
    'name': ' 顾村 '
}, {
    'id': '2.18',
    'parent': '1.4',
    'name': ' 万体馆 '
}, {
    'id': '2.19',
    'parent': '1.4',
    'name': ' 上海南站 '
}, {
    'id': '2.20',
    'parent': '1.4',
    'name': ' 徐家汇 '
}, {
    'id': '2.21',
    'parent': '1.4',
    'name': ' 徐家汇  徐虹中路 20'
}, {
    'id': '2.22',
    'parent': '1.4',
    'name': ' 淮海西路 '
}, {
    'id': '2.23',
    'parent': '1.4',
    'name': ' 漕河泾 '
}, {
    'id': '2.24',
    'parent': '1.4',
    'name': ' 田林 '
}, {
    'id': '2.25',
    'parent': '1.4',
    'name': ' 衡山路/肇嘉浜 '
}, {
    'id': '2.26',
    'parent': '1.4',
    'name': ' 龙华 '
}, {
    'id': '2.27',
    'parent': '1.5',
    'name': ' 中山北路 '
}, {
    'id': '2.28',
    'parent': '1.5',
    'name': ' 中远两湾城 '
}, {
    'id': '2.29',
    'parent': '1.5',
    'name': ' 曹杨 '
}, {
    'id': '2.30',
    'parent': '1.5',
    'name': ' 李子园 '
}, {
    'id': '2.31',
    'parent': '1.5',
    'name': ' 武宁路 '
}, {
    'id': '2.32',
    'parent': '1.5',
    'name': ' 甘泉宜川 '
}, {
    'id': '2.33',
    'parent': '1.5',
    'name': ' 真如 '
}, {
    'id': '2.34',
    'parent': '1.5',
    'name': ' 长寿路 '
}, {
    'id': '2.35',
    'parent': '1.5',
    'name': ' 长风商务区 '
}, {
    'id': '2.36',
    'parent': '1.5',
    'name': ' 长风商务区  中江路838'
}, {
    'id': '2.37',
    'parent': '1.6',
    'name': ' 中原地区 '
}, {
    'id': '2.38',
    'parent': '1.6',
    'name': ' 五角场 '
}, {
    'id': '2.39',
    'parent': '1.6',
    'name': ' 平凉/杨浦外滩 '
}, {
    'id': '2.40',
    'parent': '1.6',
    'name': ' 控江 '
}, {
    'id': '2.41',
    'parent': '1.6',
    'name': ' 新江湾城 '
}, {
    'id': '2.42',
    'parent': '1.6',
    'name': ' 鞍山 '
}, {
    'id': '2.43',
    'parent': '1.6',
    'name': ' 黄兴公园 '
}, {
    'id': '2.44',
    'parent': '1.7',
    'name': ' 九亭 '
}, {
    'id': '2.45',
    'parent': '1.7',
    'name': ' 松江 '
}, {
    'id': '2.46',
    'parent': '1.8',
    'name': ' 三林 '
}, {
    'id': '2.47',
    'parent': '1.8',
    'name': ' 上南地区 '
}, {
    'id': '2.48',
    'parent': '1.8',
    'name': ' 世博 '
}, {
    'id': '2.49',
    'parent': '1.8',
    'name': ' 世纪公园 '
}, {
    'id': '2.50',
    'parent': '1.8',
    'name': ' 八佰伴 '
}, {
    'id': '2.51',
    'parent': '1.8',
    'name': ' 北蔡/塘桥 '
}, {
    'id': '2.52',
    'parent': '1.8',
    'name': ' 周浦 '
}, {
    'id': '2.53',
    'parent': '1.8',
    'name': ' 外高桥 '
}, {
    'id': '2.54',
    'parent': '1.8',
    'name': ' 外高桥  奥纳路79号2幢'
}, {
    'id': '2.55',
    'parent': '1.8',
    'name': ' 川沙 '
}, {
    'id': '2.56',
    'parent': '1.8',
    'name': ' 张江高科 '
}, {
    'id': '2.57',
    'parent': '1.8',
    'name': ' 浦东外环 '
}, {
    'id': '2.58',
    'parent': '1.8',
    'name': ' 源深洋泾 '
}, {
    'id': '2.59',
    'parent': '1.8',
    'name': ' 竹园商贸区 '
}, {
    'id': '2.60',
    'parent': '1.8',
    'name': ' 竹园商贸区  东方路985'
}, {
    'id': '2.61',
    'parent': '1.8',
    'name': ' 金桥开发区 '
}, {
    'id': '2.62',
    'parent': '1.8',
    'name': ' 陆家嘴 '
}, {
    'id': '2.63',
    'parent': '1.9',
    'name': ' 临平/和平公园 '
}, {
    'id': '2.64',
    'parent': '1.9',
    'name': ' 凉城路/虹口足球场 '
}, {
    'id': '2.65',
    'parent': '1.9',
    'name': ' 北外滩 '
}, {
    'id': '2.66',
    'parent': '1.9',
    'name': ' 北外滩  东大名路'
}, {
    'id': '2.67',
    'parent': '1.9',
    'name': ' 四川北路 '
}, {
    'id': '2.68',
    'parent': '1.9',
    'name': ' 四川北路  沙泾路 10'
}, {
    'id': '2.69',
    'parent': '1.9',
    'name': ' 曲阳 '
}, {
    'id': '2.70',
    'parent': '1.10',
    'name': ' 金山商圈 '
}, {
    'id': '2.71',
    'parent': '1.11',
    'name': ' 中山公园 '
}, {
    'id': '2.72',
    'parent': '1.11',
    'name': ' 中山公园  长宁-地铁中山公园-华敏翰尊国际商务大厦'
}, {
    'id': '2.73',
    'parent': '1.11',
    'name': ' 北新泾 '
}, {
    'id': '2.74',
    'parent': '1.11',
    'name': ' 古北 '
}, {
    'id': '2.75',
    'parent': '1.11',
    'name': ' 天山路 '
}, {
    'id': '2.76',
    'parent': '1.11',
    'name': ' 延安西路 '
}, {
    'id': '2.77',
    'parent': '1.11',
    'name': ' 虹桥临空经济园区 '
}, {
    'id': '2.78',
    'parent': '1.11',
    'name': ' 虹桥开发区 '
}, {
    'id': '2.79',
    'parent': '1.12',
    'name': ' 七宝 '
}, {
    'id': '2.80',
    'parent': '1.12',
    'name': ' 华漕 '
}, {
    'id': '2.81',
    'parent': '1.12',
    'name': ' 南方商城 '
}, {
    'id': '2.82',
    'parent': '1.12',
    'name': ' 春申/老闵行 '
}, {
    'id': '2.83',
    'parent': '1.12',
    'name': ' 浦江 '
}, {
    'id': '2.84',
    'parent': '1.12',
    'name': ' 莘庄 '
}, {
    'id': '2.85',
    'parent': '1.12',
    'name': ' 虹桥镇 '
}, {
    'id': '2.86',
    'parent': '1.12',
    'name': ' 颛桥 '
}, {
    'id': '2.87',
    'parent': '1.12',
    'name': ' 龙柏 '
}, {
    'id': '2.88',
    'parent': '1.13',
    'name': ' 大宁绿地 '
}, {
    'id': '2.89',
    'parent': '1.13',
    'name': ' 彭浦 '
}, {
    'id': '2.90',
    'parent': '1.13',
    'name': ' 火车站 '
}, {
    'id': '2.91',
    'parent': '1.13',
    'name': ' 闸北公园 '
}, {
    'id': '2.92',
    'parent': '1.14',
    'name': ' 青浦 '
}, {
    'id': '2.93',
    'parent': '1.15',
    'name': ' 南京西路 '
}, {
    'id': '2.94',
    'parent': '1.15',
    'name': ' 曹家渡 '
}, {
    'id': '2.95',
    'parent': '1.15',
    'name': ' 江宁路 '
}, {
    'id': '2.96',
    'parent': '1.15',
    'name': ' 静安寺 '
}, {
    'id': '2.97',
    'parent': '1.16',
    'name': ' 人民广场 '
}, {
    'id': '2.98',
    'parent': '1.16',
    'name': ' 南京东路 '
}, {
    'id': '2.99',
    'parent': '1.16',
    'name': ' 城隍庙 '
}, {
    'id': '2.100',
    'parent': '1.16',
    'name': ' 外滩 '
}, {
    'id': '2.101',
    'parent': '1.16',
    'name': ' 老西门 '
}, {
    'id': '2.102',
    'parent': '1.16',
    'name': ' 豫园 '
}, {
    'value': 4,
    'id': '3.1',
    'parent': '2.1',
    'name': '申能国际大厦'
}, {
    'value': 2,
    'id': '3.2',
    'parent': '2.2',
    'name': '8号桥一期'
}, {
    'value': 1,
    'id': '3.3',
    'parent': '2.2',
    'name': '8号桥三期'
}, {
    'value': 5,
    'id': '3.4',
    'parent': '2.2',
    'name': '8号桥二期'
}, {
    'value': 5,
    'id': '3.5',
    'parent': '2.2',
    'name': '上海巴士大厦'
}, {
    'value': 2,
    'id': '3.6',
    'parent': '2.2',
    'name': '上置金融大厦'
}, {
    'value': 1,
    'id': '3.7',
    'parent': '2.2',
    'name': '世博浦西管理中心'
}, {
    'value': 2,
    'id': '3.8',
    'parent': '2.2',
    'name': '丽都大厦'
}, {
    'value': 1,
    'id': '3.9',
    'parent': '2.2',
    'name': '园林大厦'
}, {
    'value': 1,
    'id': '3.10',
    'parent': '2.2',
    'name': '国信商务大厦'
}, {
    'value': 1,
    'id': '3.11',
    'parent': '2.2',
    'name': '广东发展银行大厦'
}, {
    'value': 2,
    'id': '3.12',
    'parent': '2.2',
    'name': '广发大厦'
}, {
    'value': 1,
    'id': '3.13',
    'parent': '2.2',
    'name': '摩工坊'
}, {
    'value': 1,
    'id': '3.14',
    'parent': '2.2',
    'name': '斯格威国际'
}, {
    'value': 1,
    'id': '3.15',
    'parent': '2.2',
    'name': '日月光中心伯爵居'
}, {
    'value': 2,
    'id': '3.16',
    'parent': '2.2',
    'name': '智造局'
}, {
    'value': 6,
    'id': '3.17',
    'parent': '2.2',
    'name': '歌斐中心'
}, {
    'value': 3,
    'id': '3.18',
    'parent': '2.2',
    'name': '江南造船大厦'
}, {
    'value': 1,
    'id': '3.19',
    'parent': '2.2',
    'name': '海兴大厦'
}, {
    'value': 2,
    'id': '3.20',
    'parent': '2.2',
    'name': '海兴广场'
}, {
    'value': 1,
    'id': '3.21',
    'parent': '2.2',
    'name': '电科滨江中心'
}, {
    'value': 3,
    'id': '3.22',
    'parent': '2.2',
    'name': '绿地海外滩中心A幢'
}, {
    'value': 4,
    'id': '3.23',
    'parent': '2.2',
    'name': '绿地海外滩中心B幢'
}, {
    'value': 2,
    'id': '3.24',
    'parent': '2.2',
    'name': '致远大厦'
}, {
    'value': 1,
    'id': '3.25',
    'parent': '2.2',
    'name': '荣科大厦'
}, {
    'value': 4,
    'id': '3.26',
    'parent': '2.2',
    'name': '金玉兰广场'
}, {
    'value': 1,
    'id': '3.27',
    'parent': '2.3',
    'name': '汇针751创意园'
}, {
    'value': 3,
    'id': '3.28',
    'parent': '2.4',
    'name': '751国际创意工场'
}, {
    'value': 2,
    'id': '3.29',
    'parent': '2.4',
    'name': 'SOHO丽园'
}, {
    'value': 12,
    'id': '3.30',
    'parent': '2.4',
    'name': 'SOHO复兴广场'
}, {
    'value': 4,
    'id': '3.31',
    'parent': '2.4',
    'name': '上海广场'
}, {
    'value': 1,
    'id': '3.32',
    'parent': '2.4',
    'name': '上海新天地时尚广场'
}, {
    'value': 1,
    'id': '3.33',
    'parent': '2.4',
    'name': '世纪巴士大厦'
}, {
    'value': 5,
    'id': '3.34',
    'parent': '2.4',
    'name': '久事复兴大厦'
}, {
    'value': 7,
    'id': '3.35',
    'parent': '2.4',
    'name': '企业天地'
}, {
    'value': 5,
    'id': '3.36',
    'parent': '2.4',
    'name': '力宝广场'
}, {
    'value': 1,
    'id': '3.37',
    'parent': '2.4',
    'name': '卢湾建设发展大楼'
}, {
    'value': 1,
    'id': '3.38',
    'parent': '2.4',
    'name': '复兴广场'
}, {
    'value': 4,
    'id': '3.39',
    'parent': '2.4',
    'name': '新茂大厦'
}, {
    'value': 3,
    'id': '3.40',
    'parent': '2.4',
    'name': '柳林大厦'
}, {
    'value': 3,
    'id': '3.41',
    'parent': '2.4',
    'name': '永银大厦'
}, {
    'value': 1,
    'id': '3.42',
    'parent': '2.4',
    'name': '淮海金融大厦'
}, {
    'value': 3,
    'id': '3.43',
    'parent': '2.4',
    'name': '瑞安广场'
}, {
    'value': 5,
    'id': '3.44',
    'parent': '2.4',
    'name': '瑞金大厦'
}, {
    'value': 2,
    'id': '3.45',
    'parent': '2.4',
    'name': '越界世博园'
}, {
    'value': 7,
    'id': '3.46',
    'parent': '2.4',
    'name': '香港广场'
}, {
    'value': 5,
    'id': '3.47',
    'parent': '2.4',
    'name': '香港新世界大厦'
}, {
    'value': 2,
    'id': '3.48',
    'parent': '2.5',
    'name': '中冶祥腾城市广场'
}, {
    'value': 1,
    'id': '3.49',
    'parent': '2.5',
    'name': '中冶祥腾城市广场·菁英逸品'
}, {
    'value': 3,
    'id': '3.50',
    'parent': '2.5',
    'name': '南翔智地'
}, {
    'value': 2,
    'id': '3.51',
    'parent': '2.5',
    'name': '新明KIDMALL'
}, {
    'value': 6,
    'id': '3.52',
    'parent': '2.6',
    'name': '嘉定宝龙城市广场'
}, {
    'value': 2,
    'id': '3.53',
    'parent': '2.6',
    'name': '尚品SOHO'
}, {
    'value': 1,
    'id': '3.54',
    'parent': '2.6',
    'name': '日月光伯爵天地'
}, {
    'value': 2,
    'id': '3.55',
    'parent': '2.6',
    'name': '月月光伯爵天地'
}, {
    'value': 2,
    'id': '3.56',
    'parent': '2.6',
    'name': '永盛商务楼1号楼'
}, {
    'value': 3,
    'id': '3.57',
    'parent': '2.6',
    'name': '盛创企业家园'
}, {
    'value': 1,
    'id': '3.58',
    'parent': '2.7',
    'name': '嘉亭大厦'
}, {
    'value': 1,
    'id': '3.59',
    'parent': '2.8',
    'name': '上海西郊商务区-C2国际区'
}, {
    'value': 1,
    'id': '3.60',
    'parent': '2.8',
    'name': '嘉印象'
}, {
    'value': 1,
    'id': '3.61',
    'parent': '2.8',
    'name': '四方科创园'
}, {
    'value': 6,
    'id': '3.62',
    'parent': '2.8',
    'name': '慧创国际'
}, {
    'value': 1,
    'id': '3.63',
    'parent': '2.8',
    'name': '慧创国际C-2区'
}, {
    'value': 3,
    'id': '3.64',
    'parent': '2.8',
    'name': '歆翱商务大厦'
}, {
    'value': 1,
    'id': '3.65',
    'parent': '2.8',
    'name': '歆翱国际电商大厦'
}, {
    'value': 10,
    'id': '3.66',
    'parent': '2.8',
    'name': '江桥万达广场'
}, {
    'value': 1,
    'id': '3.67',
    'parent': '2.8',
    'name': '申窑艺术中心'
}, {
    'value': 2,
    'id': '3.68',
    'parent': '2.9',
    'name': '昇PARK创意园'
}, {
    'value': 3,
    'id': '3.69',
    'parent': '2.10',
    'name': '北外环信息产业园'
}, {
    'value': 4,
    'id': '3.70',
    'parent': '2.10',
    'name': '泰德科技园'
}, {
    'value': 2,
    'id': '3.71',
    'parent': '2.11',
    'name': '城市新汇'
}, {
    'value': 20,
    'id': '3.72',
    'parent': '2.11',
    'name': '宝山万达广场'
}, {
    'value': 3,
    'id': '3.73',
    'parent': '2.11',
    'name': '永谊大厦'
}, {
    'value': 2,
    'id': '3.74',
    'parent': '2.11',
    'name': '绿地风尚天地'
}, {
    'value': 2,
    'id': '3.75',
    'parent': '2.11',
    'name': '绿地风尚天地广场'
}, {
    'value': 1,
    'id': '3.76',
    'parent': '2.11',
    'name': '骏利财富大厦'
}, {
    'value': 1,
    'id': '3.77',
    'parent': '2.12',
    'name': '智慧七立方'
}, {
    'value': 1,
    'id': '3.78',
    'parent': '2.13',
    'name': '大华虎城第三空间'
}, {
    'value': 2,
    'id': '3.79',
    'parent': '2.13',
    'name': '尚大国际'
}, {
    'value': 1,
    'id': '3.80',
    'parent': '2.13',
    'name': '齐成晟园'
}, {
    'value': 1,
    'id': '3.81',
    'parent': '2.14',
    'name': '岛里创新园'
}, {
    'value': 1,
    'id': '3.82',
    'parent': '2.15',
    'name': '中铁北城时代'
}, {
    'value': 2,
    'id': '3.83',
    'parent': '2.16',
    'name': '中成智谷'
}, {
    'value': 1,
    'id': '3.84',
    'parent': '2.16',
    'name': '华滋奔腾大厦'
}, {
    'value': 3,
    'id': '3.85',
    'parent': '2.17',
    'name': '新宝中心'
}, {
    'value': 2,
    'id': '3.86',
    'parent': '2.17',
    'name': '智慧湾科创园'
}, {
    'value': 1,
    'id': '3.87',
    'parent': '2.17',
    'name': '梓坤科技园'
}, {
    'value': 1,
    'id': '3.88',
    'parent': '2.17',
    'name': '绿地公元1860'
}, {
    'value': 5,
    'id': '3.89',
    'parent': '2.17',
    'name': '绿地公园广场'
}, {
    'value': 1,
    'id': '3.90',
    'parent': '2.17',
    'name': '绿地北郊广场'
}, {
    'value': 1,
    'id': '3.91',
    'parent': '2.18',
    'name': '上海国峰科技大厦'
}, {
    'value': 1,
    'id': '3.92',
    'parent': '2.18',
    'name': '上海望族城大厦'
}, {
    'value': 1,
    'id': '3.93',
    'parent': '2.18',
    'name': '中煌大厦'
}, {
    'value': 5,
    'id': '3.94',
    'parent': '2.18',
    'name': '兆丰环球大厦'
}, {
    'value': 9,
    'id': '3.95',
    'parent': '2.18',
    'name': '光启城'
}, {
    'value': 3,
    'id': '3.96',
    'parent': '2.18',
    'name': '光启文化广场'
}, {
    'value': 1,
    'id': '3.97',
    'parent': '2.18',
    'name': '南洋1931'
}, {
    'value': 2,
    'id': '3.98',
    'parent': '2.18',
    'name': '嘉汇国际广场'
}, {
    'value': 1,
    'id': '3.99',
    'parent': '2.18',
    'name': '天华信息科技园'
}, {
    'value': 1,
    'id': '3.100',
    'parent': '2.18',
    'name': '徐汇晶典大厦'
}, {
    'value': 1,
    'id': '3.101',
    'parent': '2.18',
    'name': '徐汇苑大厦'
}, {
    'value': 1,
    'id': '3.102',
    'parent': '2.18',
    'name': '明申中心大厦'
}, {
    'value': 1,
    'id': '3.103',
    'parent': '2.18',
    'name': '枫林国际大厦'
}, {
    'value': 3,
    'id': '3.104',
    'parent': '2.18',
    'name': '森本大厦'
}, {
    'value': 5,
    'id': '3.105',
    'parent': '2.18',
    'name': '永升大厦'
}, {
    'value': 7,
    'id': '3.106',
    'parent': '2.18',
    'name': '汇智大厦'
}, {
    'value': 1,
    'id': '3.107',
    'parent': '2.18',
    'name': '海洋石油大厦'
}, {
    'value': 1,
    'id': '3.108',
    'parent': '2.18',
    'name': '环线广场'
}, {
    'value': 1,
    'id': '3.109',
    'parent': '2.18',
    'name': '腾飞大厦'
}, {
    'value': 8,
    'id': '3.110',
    'parent': '2.18',
    'name': '飞洲国际广场'
}, {
    'value': 1,
    'id': '3.111',
    'parent': '2.19',
    'name': '一加投资创意园'
}, {
    'value': 1,
    'id': '3.112',
    'parent': '2.19',
    'name': '万街303'
}, {
    'value': 3,
    'id': '3.113',
    'parent': '2.19',
    'name': '中星城'
}, {
    'value': 2,
    'id': '3.114',
    'parent': '2.19',
    'name': '徐汇易园'
}, {
    'value': 3,
    'id': '3.115',
    'parent': '2.19',
    'name': '漕河泾易园'
}, {
    'value': 1,
    'id': '3.116',
    'parent': '2.19',
    'name': '美通科创空间'
}, {
    'value': 1,
    'id': '3.117',
    'parent': '2.19',
    'name': '越界智慧谷'
}, {
    'value': 5,
    'id': '3.118',
    'parent': '2.20',
    'name': 'D1国际创意空间'
}, {
    'value': 1,
    'id': '3.119',
    'parent': '2.20',
    'name': 'X2创意园区2期'
}, {
    'value': 3,
    'id': '3.120',
    'parent': '2.20',
    'name': 'X2创意空间'
}, {
    'value': 2,
    'id': '3.121',
    'parent': '2.20',
    'name': '七建大厦'
}, {
    'value': 1,
    'id': '3.122',
    'parent': '2.20',
    'name': '上海地产大厦'
}, {
    'value': 2,
    'id': '3.123',
    'parent': '2.20',
    'name': '上海实业大厦'
}, {
    'value': 8,
    'id': '3.124',
    'parent': '2.20',
    'name': '中城国际大厦'
}, {
    'value': 1,
    'id': '3.125',
    'parent': '2.20',
    'name': '中福实业大厦'
}, {
    'value': 6,
    'id': '3.126',
    'parent': '2.20',
    'name': '中金国际广场'
}, {
    'value': 1,
    'id': '3.127',
    'parent': '2.20',
    'name': '之俊大厦主楼'
}, {
    'value': 1,
    'id': '3.128',
    'parent': '2.20',
    'name': '亚都商务楼'
}, {
    'value': 1,
    'id': '3.129',
    'parent': '2.20',
    'name': '伍佰视觉园'
}, {
    'value': 1,
    'id': '3.130',
    'parent': '2.20',
    'name': '元福大厦'
}, {
    'value': 1,
    'id': '3.131',
    'parent': '2.20',
    'name': '北科大厦'
}, {
    'value': 3,
    'id': '3.132',
    'parent': '2.20',
    'name': '华宜大厦'
}, {
    'value': 3,
    'id': '3.133',
    'parent': '2.20',
    'name': '华鑫天地'
}, {
    'value': 2,
    'id': '3.134',
    'parent': '2.20',
    'name': '南洋实业大楼'
}, {
    'value': 1,
    'id': '3.135',
    'parent': '2.20',
    'name': '嘉汇广场'
}, {
    'value': 6,
    'id': '3.136',
    'parent': '2.20',
    'name': '圣爱广场'
}, {
    'value': 5,
    'id': '3.137',
    'parent': '2.20',
    'name': '均瑶国际广场'
}, {
    'value': 7,
    'id': '3.138',
    'parent': '2.20',
    'name': '城开国际大厦'
}, {
    'value': 2,
    'id': '3.139',
    'parent': '2.20',
    'name': '宏汇国际广场'
}, {
    'value': 5,
    'id': '3.140',
    'parent': '2.20',
    'name': '尚光徐汇中心'
}, {
    'value': 1,
    'id': '3.141',
    'parent': '2.20',
    'name': '徐家汇国际'
}, {
    'value': 2,
    'id': '3.142',
    'parent': '2.20',
    'name': '徐家汇独栋花园办公楼'
}, {
    'value': 6,
    'id': '3.143',
    'parent': '2.20',
    'name': '徐汇万科中心'
}, {
    'value': 1,
    'id': '3.144',
    'parent': '2.20',
    'name': '数娱大厦'
}, {
    'value': 2,
    'id': '3.145',
    'parent': '2.20',
    'name': '汇京国际广场'
}, {
    'value': 1,
    'id': '3.146',
    'parent': '2.20',
    'name': '汇嘉大厦'
}, {
    'value': 1,
    'id': '3.147',
    'parent': '2.20',
    'name': '汇峰大厦'
}, {
    'value': 3,
    'id': '3.148',
    'parent': '2.20',
    'name': '汇鑫国际大厦'
}, {
    'value': 3,
    'id': '3.149',
    'parent': '2.20',
    'name': '汇银广场'
}, {
    'value': 1,
    'id': '3.150',
    'parent': '2.20',
    'name': '港汇中心二座'
}, {
    'value': 9,
    'id': '3.151',
    'parent': '2.20',
    'name': '港汇恒隆广场'
}, {
    'value': 1,
    'id': '3.152',
    'parent': '2.20',
    'name': '环贸iapm'
}, {
    'value': 1,
    'id': '3.153',
    'parent': '2.20',
    'name': '申峰大厦'
}, {
    'value': 1,
    'id': '3.154',
    'parent': '2.20',
    'name': '申通信息广场'
}, {
    'value': 1,
    'id': '3.155',
    'parent': '2.20',
    'name': '百汇园'
}, {
    'value': 1,
    'id': '3.156',
    'parent': '2.20',
    'name': '盛源恒华大厦'
}, {
    'value': 5,
    'id': '3.157',
    'parent': '2.20',
    'name': '联峰汇'
}, {
    'value': 1,
    'id': '3.158',
    'parent': '2.20',
    'name': '金轩大厦'
}, {
    'value': 1,
    'id': '3.159',
    'parent': '2.20',
    'name': '金钟大厦'
}, {
    'value': 2,
    'id': '3.160',
    'parent': '2.20',
    'name': '飞雕国际大厦'
}, {
    'value': 1,
    'id': '3.161',
    'parent': '2.21',
    'name': '西岸创意园区'
}, {
    'value': 1,
    'id': '3.162',
    'parent': '2.22',
    'name': '上海环茂广场'
}, {
    'value': 2,
    'id': '3.163',
    'parent': '2.22',
    'name': '世纪商贸广场'
}, {
    'value': 1,
    'id': '3.164',
    'parent': '2.22',
    'name': '云海大厦'
}, {
    'value': 3,
    'id': '3.165',
    'parent': '2.22',
    'name': '嘉华中心'
}, {
    'value': 2,
    'id': '3.166',
    'parent': '2.22',
    'name': '武康庭'
}, {
    'value': 2,
    'id': '3.167',
    'parent': '2.22',
    'name': '淮海国际广场'
}, {
    'value': 5,
    'id': '3.168',
    'parent': '2.23',
    'name': 'H88越虹广场'
}, {
    'value': 3,
    'id': '3.169',
    'parent': '2.23',
    'name': '上海光大会展中心'
}, {
    'value': 1,
    'id': '3.170',
    'parent': '2.23',
    'name': '上海南站德必易园'
}, {
    'value': 2,
    'id': '3.171',
    'parent': '2.23',
    'name': '上海桂林聚科都市科技园'
}, {
    'value': 2,
    'id': '3.172',
    'parent': '2.23',
    'name': '上海诚达创意产业园区'
}, {
    'value': 1,
    'id': '3.173',
    'parent': '2.23',
    'name': '乐业天地创意园'
}, {
    'value': 2,
    'id': '3.174',
    'parent': '2.23',
    'name': '企业总部园区'
}, {
    'value': 4,
    'id': '3.175',
    'parent': '2.23',
    'name': '光启园'
}, {
    'value': 1,
    'id': '3.176',
    'parent': '2.23',
    'name': '光大会展中心D座'
}, {
    'value': 1,
    'id': '3.177',
    'parent': '2.23',
    'name': '凤凰科技园'
}, {
    'value': 2,
    'id': '3.178',
    'parent': '2.23',
    'name': '凯科国际大厦'
}, {
    'value': 3,
    'id': '3.179',
    'parent': '2.23',
    'name': '华纳商务中心'
}, {
    'value': 11,
    'id': '3.180',
    'parent': '2.23',
    'name': '华鑫中心'
}, {
    'value': 4,
    'id': '3.181',
    'parent': '2.23',
    'name': '合川大厦'
}, {
    'value': 2,
    'id': '3.182',
    'parent': '2.23',
    'name': '天华信息科技服务园'
}, {
    'value': 4,
    'id': '3.183',
    'parent': '2.23',
    'name': '宝石园大厦'
}, {
    'value': 1,
    'id': '3.184',
    'parent': '2.23',
    'name': '徐汇创意园'
}, {
    'value': 1,
    'id': '3.185',
    'parent': '2.23',
    'name': '怡虹科技园'
}, {
    'value': 1,
    'id': '3.186',
    'parent': '2.23',
    'name': '新业大楼'
}, {
    'value': 8,
    'id': '3.187',
    'parent': '2.23',
    'name': '新意城'
}, {
    'value': 2,
    'id': '3.188',
    'parent': '2.23',
    'name': '新汇园'
}, {
    'value': 5,
    'id': '3.189',
    'parent': '2.23',
    'name': '新漕河泾国际商务中心'
}, {
    'value': 1,
    'id': '3.190',
    'parent': '2.23',
    'name': '新银大厦'
}, {
    'value': 1,
    'id': '3.191',
    'parent': '2.23',
    'name': '明申商务广场'
}, {
    'value': 6,
    'id': '3.192',
    'parent': '2.23',
    'name': '星联研发楼'
}, {
    'value': 3,
    'id': '3.193',
    'parent': '2.23',
    'name': '桂果园'
}, {
    'value': 1,
    'id': '3.194',
    'parent': '2.23',
    'name': '桂箐路产业园'
}, {
    'value': 10,
    'id': '3.195',
    'parent': '2.23',
    'name': '民润大厦'
}, {
    'value': 4,
    'id': '3.196',
    'parent': '2.23',
    'name': '泓毅大厦'
}, {
    'value': 1,
    'id': '3.197',
    'parent': '2.23',
    'name': '漕河泾国际商务中心'
}, {
    'value': 2,
    'id': '3.198',
    'parent': '2.23',
    'name': '漕河泾现代服务业园区'
}, {
    'value': 1,
    'id': '3.199',
    'parent': '2.23',
    'name': '现代物流大厦'
}, {
    'value': 2,
    'id': '3.200',
    'parent': '2.23',
    'name': '田林园'
}, {
    'value': 2,
    'id': '3.201',
    'parent': '2.23',
    'name': '研祥科技大楼'
}, {
    'value': 5,
    'id': '3.202',
    'parent': '2.23',
    'name': '科技产业化大楼'
}, {
    'value': 4,
    'id': '3.203',
    'parent': '2.23',
    'name': '科技绿洲'
}, {
    'value': 2,
    'id': '3.204',
    'parent': '2.23',
    'name': '科汇大厦'
}, {
    'value': 1,
    'id': '3.205',
    'parent': '2.23',
    'name': '立明大厦'
}, {
    'value': 6,
    'id': '3.206',
    'parent': '2.23',
    'name': '莲花大厦'
}, {
    'value': 6,
    'id': '3.207',
    'parent': '2.23',
    'name': '虹桥国际商务广场'
}, {
    'value': 2,
    'id': '3.208',
    'parent': '2.23',
    'name': '虹漕园'
}, {
    'value': 1,
    'id': '3.209',
    'parent': '2.23',
    'name': '虹钦园'
}, {
    'value': 1,
    'id': '3.210',
    'parent': '2.23',
    'name': '贝岭技术研发中心'
}, {
    'value': 5,
    'id': '3.211',
    'parent': '2.23',
    'name': '远中产业园'
}, {
    'value': 1,
    'id': '3.212',
    'parent': '2.23',
    'name': '远中科研大楼'
}, {
    'value': 9,
    'id': '3.213',
    'parent': '2.23',
    'name': '钦汇园'
}, {
    'value': 19,
    'id': '3.214',
    'parent': '2.24',
    'name': 'SVA越界'
}, {
    'value': 1,
    'id': '3.215',
    'parent': '2.24',
    'name': '上海主角'
}, {
    'value': 5,
    'id': '3.216',
    'parent': '2.24',
    'name': '普天科技园'
}, {
    'value': 6,
    'id': '3.217',
    'parent': '2.24',
    'name': '汇阳广场'
}, {
    'value': 2,
    'id': '3.218',
    'parent': '2.24',
    'name': '漕河泾凤凰园'
}, {
    'value': 2,
    'id': '3.219',
    'parent': '2.24',
    'name': '锦辉大厦'
}, {
    'value': 2,
    'id': '3.220',
    'parent': '2.24',
    'name': '鼎力创意园'
}, {
    'value': 1,
    'id': '3.221',
    'parent': '2.25',
    'name': '亚太企业大厦'
}, {
    'value': 2,
    'id': '3.222',
    'parent': '2.25',
    'name': '坤阳国际商务广场'
}, {
    'value': 2,
    'id': '3.223',
    'parent': '2.25',
    'name': '尚街LOFT'
}, {
    'value': 1,
    'id': '3.224',
    'parent': '2.25',
    'name': '枫林创意园'
}, {
    'value': 11,
    'id': '3.225',
    'parent': '2.25',
    'name': '永丰国际广场'
}, {
    'value': 2,
    'id': '3.226',
    'parent': '2.25',
    'name': '永嘉庭'
}, {
    'value': 3,
    'id': '3.227',
    'parent': '2.25',
    'name': '美奂大厦'
}, {
    'value': 2,
    'id': '3.228',
    'parent': '2.25',
    'name': '衡安大楼'
}, {
    'value': 1,
    'id': '3.229',
    'parent': '2.25',
    'name': '青松城'
}, {
    'value': 3,
    'id': '3.230',
    'parent': '2.26',
    'name': '2577创意大院'
}, {
    'value': 1,
    'id': '3.231',
    'parent': '2.26',
    'name': 'L777新媒体产业园'
}, {
    'value': 3,
    'id': '3.232',
    'parent': '2.26',
    'name': '上海纺运物流商务中心'
}, {
    'value': 6,
    'id': '3.233',
    'parent': '2.26',
    'name': '上海绿地中心一期'
}, {
    'value': 2,
    'id': '3.234',
    'parent': '2.26',
    'name': '徐汇大树下新媒体创意园'
}, {
    'value': 1,
    'id': '3.235',
    'parent': '2.26',
    'name': '绿地中心二期写字楼'
}, {
    'value': 13,
    'id': '3.236',
    'parent': '2.26',
    'name': '绿地汇中心'
}, {
    'value': 1,
    'id': '3.237',
    'parent': '2.27',
    'name': '万千大厦'
}, {
    'value': 1,
    'id': '3.238',
    'parent': '2.27',
    'name': '中一国际商务大厦'
}, {
    'value': 2,
    'id': '3.239',
    'parent': '2.27',
    'name': '中期大厦'
}, {
    'value': 1,
    'id': '3.240',
    'parent': '2.27',
    'name': '加减乘除创意园'
}, {
    'value': 3,
    'id': '3.241',
    'parent': '2.27',
    'name': '华源世界广场'
}, {
    'value': 1,
    'id': '3.242',
    'parent': '2.27',
    'name': '格林德必易园'
}, {
    'value': 4,
    'id': '3.243',
    'parent': '2.27',
    'name': '浦发广场写字楼'
}, {
    'value': 6,
    'id': '3.244',
    'parent': '2.27',
    'name': '浦发财富广场'
}, {
    'value': 3,
    'id': '3.245',
    'parent': '2.27',
    'name': '飞洲时代大厦'
}, {
    'value': 2,
    'id': '3.246',
    'parent': '2.28',
    'name': '万业新阶'
}, {
    'value': 2,
    'id': '3.247',
    'parent': '2.29',
    'name': '50智慧产业科技园'
}, {
    'value': 1,
    'id': '3.248',
    'parent': '2.29',
    'name': '50智慧园'
}, {
    'value': 4,
    'id': '3.249',
    'parent': '2.29',
    'name': '上海月星环球港'
}, {
    'value': 3,
    'id': '3.250',
    'parent': '2.29',
    'name': '中关村科技大厦'
}, {
    'value': 2,
    'id': '3.251',
    'parent': '2.29',
    'name': '中联大厦'
}, {
    'value': 1,
    'id': '3.252',
    'parent': '2.29',
    'name': '尚诚国际'
}, {
    'value': 1,
    'id': '3.253',
    'parent': '2.29',
    'name': '尚诚国际大厦'
}, {
    'value': 1,
    'id': '3.254',
    'parent': '2.29',
    'name': '开伦智汇园（普陀）'
}, {
    'value': 5,
    'id': '3.255',
    'parent': '2.29',
    'name': '我格广场'
}, {
    'value': 2,
    'id': '3.256',
    'parent': '2.29',
    'name': '春之声大厦'
}, {
    'value': 4,
    'id': '3.257',
    'parent': '2.29',
    'name': '曹杨尚城国际'
}, {
    'value': 7,
    'id': '3.258',
    'parent': '2.29',
    'name': '杰地大厦'
}, {
    'value': 1,
    'id': '3.259',
    'parent': '2.29',
    'name': '欧爱喜商务广场'
}, {
    'value': 2,
    'id': '3.260',
    'parent': '2.29',
    'name': '汇融大厦'
}, {
    'value': 1,
    'id': '3.261',
    'parent': '2.29',
    'name': '申汉大厦'
}, {
    'value': 1,
    'id': '3.262',
    'parent': '2.29',
    'name': '盛源科技园'
}, {
    'value': 1,
    'id': '3.263',
    'parent': '2.29',
    'name': '绿地同创大厦'
}, {
    'value': 5,
    'id': '3.264',
    'parent': '2.29',
    'name': '绿地和创大厦'
}, {
    'value': 4,
    'id': '3.265',
    'parent': '2.29',
    'name': '绿地科创大厦'
}, {
    'value': 1,
    'id': '3.266',
    'parent': '2.29',
    'name': '绿洲广场'
}, {
    'value': 2,
    'id': '3.267',
    'parent': '2.29',
    'name': '联合大厦'
}, {
    'value': 4,
    'id': '3.268',
    'parent': '2.29',
    'name': '近铁云大厦'
}, {
    'value': 6,
    'id': '3.269',
    'parent': '2.29',
    'name': '长城大厦'
}, {
    'value': 1,
    'id': '3.270',
    'parent': '2.29',
    'name': '鸿运大厦'
}, {
    'value': 1,
    'id': '3.271',
    'parent': '2.30',
    'name': '麦腾创业天地'
}, {
    'value': 2,
    'id': '3.272',
    'parent': '2.31',
    'name': '丽晶阳光大厦'
}, {
    'value': 2,
    'id': '3.273',
    'parent': '2.31',
    'name': '智慧广场'
}, {
    'value': 3,
    'id': '3.274',
    'parent': '2.32',
    'name': '绿地威科国际商业广场'
}, {
    'value': 1,
    'id': '3.275',
    'parent': '2.32',
    'name': '颐正大厦'
}, {
    'value': 1,
    'id': '3.276',
    'parent': '2.33',
    'name': 'MINI公馆'
}, {
    'value': 6,
    'id': '3.277',
    'parent': '2.33',
    'name': '品尊国际中心'
}, {
    'value': 3,
    'id': '3.278',
    'parent': '2.33',
    'name': '天汇广场'
}, {
    'value': 1,
    'id': '3.279',
    'parent': '2.33',
    'name': '康健商务广场'
}, {
    'value': 1,
    'id': '3.280',
    'parent': '2.33',
    'name': '康建商务广场'
}, {
    'value': 2,
    'id': '3.281',
    'parent': '2.33',
    'name': '李子园大厦'
}, {
    'value': 1,
    'id': '3.282',
    'parent': '2.33',
    'name': '沪西德必易园'
}, {
    'value': 3,
    'id': '3.283',
    'parent': '2.33',
    'name': '耀光中环国际大厦'
}, {
    'value': 8,
    'id': '3.284',
    'parent': '2.33',
    'name': '近铁城市广场'
}, {
    'value': 1,
    'id': '3.285',
    'parent': '2.33',
    'name': '金沙江商务广场'
}, {
    'value': 1,
    'id': '3.286',
    'parent': '2.33',
    'name': '高尚领域'
}, {
    'value': 1,
    'id': '3.287',
    'parent': '2.33',
    'name': '鸿海大厦'
}, {
    'value': 1,
    'id': '3.288',
    'parent': '2.34',
    'name': '世纪商务大厦'
}, {
    'value': 1,
    'id': '3.289',
    'parent': '2.34',
    'name': '中华1912创意产业园'
}, {
    'value': 1,
    'id': '3.290',
    'parent': '2.34',
    'name': '中国港中旅大厦'
}, {
    'value': 3,
    'id': '3.291',
    'parent': '2.34',
    'name': '中港汇大厦'
}, {
    'value': 2,
    'id': '3.292',
    'parent': '2.34',
    'name': '元茂金豪大厦'
}, {
    'value': 2,
    'id': '3.293',
    'parent': '2.34',
    'name': '华生大厦'
}, {
    'value': 3,
    'id': '3.294',
    'parent': '2.34',
    'name': '友力国际大厦'
}, {
    'value': 2,
    'id': '3.295',
    'parent': '2.34',
    'name': '宝华大厦'
}, {
    'value': 1,
    'id': '3.296',
    'parent': '2.34',
    'name': '富丽大厦'
}, {
    'value': 4,
    'id': '3.297',
    'parent': '2.34',
    'name': '平高国际广场'
}, {
    'value': 1,
    'id': '3.298',
    'parent': '2.34',
    'name': '开隆大厦'
}, {
    'value': 3,
    'id': '3.299',
    'parent': '2.34',
    'name': '悦达国际大厦'
}, {
    'value': 1,
    'id': '3.300',
    'parent': '2.34',
    'name': '沙田大厦'
}, {
    'value': 9,
    'id': '3.301',
    'parent': '2.34',
    'name': '源达大厦'
}, {
    'value': 5,
    'id': '3.302',
    'parent': '2.34',
    'name': '财富时代大厦'
}, {
    'value': 1,
    'id': '3.303',
    'parent': '2.34',
    'name': '银座企业中心'
}, {
    'value': 1,
    'id': '3.304',
    'parent': '2.34',
    'name': '长久商务中心'
}, {
    'value': 1,
    'id': '3.305',
    'parent': '2.34',
    'name': '飞雕商务大厦'
}, {
    'value': 1,
    'id': '3.306',
    'parent': '2.35',
    'name': '上海跨国采购中心'
}, {
    'value': 1,
    'id': '3.307',
    'parent': '2.35',
    'name': '中天新世纪'
}, {
    'value': 1,
    'id': '3.308',
    'parent': '2.35',
    'name': '创邑金沙谷'
}, {
    'value': 8,
    'id': '3.309',
    'parent': '2.35',
    'name': '北岸长风'
}, {
    'value': 3,
    'id': '3.310',
    'parent': '2.35',
    'name': '华宏商务中心'
}, {
    'value': 5,
    'id': '3.311',
    'parent': '2.35',
    'name': '国盛中心'
}, {
    'value': 3,
    'id': '3.312',
    'parent': '2.35',
    'name': '敦奴大厦'
}, {
    'value': 4,
    'id': '3.313',
    'parent': '2.35',
    'name': '旭辉世纪广场'
}, {
    'value': 1,
    'id': '3.314',
    'parent': '2.35',
    'name': '普罗娜商务广场'
}, {
    'value': 3,
    'id': '3.315',
    'parent': '2.35',
    'name': '汇银铭尊'
}, {
    'value': 6,
    'id': '3.316',
    'parent': '2.35',
    'name': '海亮大厦'
}, {
    'value': 1,
    'id': '3.317',
    'parent': '2.35',
    'name': '清水湾大酒店'
}, {
    'value': 1,
    'id': '3.318',
    'parent': '2.35',
    'name': '红星世贸大厦'
}, {
    'value': 28,
    'id': '3.319',
    'parent': '2.35',
    'name': '绿洲中环中心'
}, {
    'value': 1,
    'id': '3.320',
    'parent': '2.35',
    'name': '绿洲中环中心1号楼'
}, {
    'value': 1,
    'id': '3.321',
    'parent': '2.35',
    'name': '绿洲中环中心3号楼'
}, {
    'value': 1,
    'id': '3.322',
    'parent': '2.35',
    'name': '绿洲中环中心6号楼'
}, {
    'value': 3,
    'id': '3.323',
    'parent': '2.35',
    'name': '苏宁天御国际广场'
}, {
    'value': 6,
    'id': '3.324',
    'parent': '2.35',
    'name': '赢华国际广场'
}, {
    'value': 1,
    'id': '3.325',
    'parent': '2.35',
    'name': '金沙商务广场'
}, {
    'value': 2,
    'id': '3.326',
    'parent': '2.35',
    'name': '金环商务花园'
}, {
    'value': 1,
    'id': '3.327',
    'parent': '2.36',
    'name': '华大科技园'
}, {
    'value': 1,
    'id': '3.328',
    'parent': '2.37',
    'name': '波司登大厦'
}, {
    'value': 10,
    'id': '3.329',
    'parent': '2.38',
    'name': '上海合生国际广场'
}, {
    'value': 1,
    'id': '3.330',
    'parent': '2.38',
    'name': '东上海中心'
}, {
    'value': 7,
    'id': '3.331',
    'parent': '2.38',
    'name': '东方蓝海国际广场'
}, {
    'value': 2,
    'id': '3.332',
    'parent': '2.38',
    'name': '中天大厦'
}, {
    'value': 2,
    'id': '3.333',
    'parent': '2.38',
    'name': '中环国际大厦'
}, {
    'value': 3,
    'id': '3.334',
    'parent': '2.38',
    'name': '中航天盛广场'
}, {
    'value': 10,
    'id': '3.335',
    'parent': '2.38',
    'name': '五角丰达'
}, {
    'value': 2,
    'id': '3.336',
    'parent': '2.38',
    'name': '五角丰达二期'
}, {
    'value': 1,
    'id': '3.337',
    'parent': '2.38',
    'name': '五角场800号艺术区'
}, {
    'value': 4,
    'id': '3.338',
    'parent': '2.38',
    'name': '五角场万达广场'
}, {
    'value': 1,
    'id': '3.339',
    'parent': '2.38',
    'name': '凯迪金融大厦'
}, {
    'value': 1,
    'id': '3.340',
    'parent': '2.38',
    'name': '创智坊'
}, {
    'value': 5,
    'id': '3.341',
    'parent': '2.38',
    'name': '创智天地'
}, {
    'value': 2,
    'id': '3.342',
    'parent': '2.38',
    'name': '创智天地广场三期'
}, {
    'value': 5,
    'id': '3.343',
    'parent': '2.38',
    'name': '同和国际大厦'
}, {
    'value': 1,
    'id': '3.344',
    'parent': '2.38',
    'name': '君庭广场'
}, {
    'value': 8,
    'id': '3.345',
    'parent': '2.38',
    'name': '国正中心'
}, {
    'value': 1,
    'id': '3.346',
    'parent': '2.38',
    'name': '国阳大厦'
}, {
    'value': 1,
    'id': '3.347',
    'parent': '2.38',
    'name': '城市概念创意园区'
}, {
    'value': 4,
    'id': '3.348',
    'parent': '2.38',
    'name': '复旦科技园大厦'
}, {
    'value': 4,
    'id': '3.349',
    'parent': '2.38',
    'name': '尚浦领世'
}, {
    'value': 3,
    'id': '3.350',
    'parent': '2.38',
    'name': '平盛大厦'
}, {
    'value': 1,
    'id': '3.351',
    'parent': '2.38',
    'name': '怡富商务广场'
}, {
    'value': 1,
    'id': '3.352',
    'parent': '2.38',
    'name': '杨浦科技大厦'
}, {
    'value': 1,
    'id': '3.353',
    'parent': '2.38',
    'name': '海上硕和城SOHO商务中心'
}, {
    'value': 5,
    'id': '3.354',
    'parent': '2.38',
    'name': '绿地汇创国际广场'
}, {
    'value': 5,
    'id': '3.355',
    'parent': '2.38',
    'name': '绿地能源大厦'
}, {
    'value': 6,
    'id': '3.356',
    'parent': '2.38',
    'name': '蓝天大厦'
}, {
    'value': 4,
    'id': '3.357',
    'parent': '2.38',
    'name': '财富国际广场'
}, {
    'value': 1,
    'id': '3.358',
    'parent': '2.38',
    'name': '金岛大厦'
}, {
    'value': 1,
    'id': '3.359',
    'parent': '2.38',
    'name': '长阳谷'
}, {
    'value': 1,
    'id': '3.360',
    'parent': '2.39',
    'name': '上海电力国家大学科技园'
}, {
    'value': 5,
    'id': '3.361',
    'parent': '2.39',
    'name': '东方渔人码头'
}, {
    'value': 1,
    'id': '3.362',
    'parent': '2.39',
    'name': '互联宝地'
}, {
    'value': 6,
    'id': '3.363',
    'parent': '2.39',
    'name': '保利绿地'
}, {
    'value': 2,
    'id': '3.364',
    'parent': '2.39',
    'name': '宝地广场'
}, {
    'value': 1,
    'id': '3.365',
    'parent': '2.39',
    'name': '尚凯商务大厦'
}, {
    'value': 8,
    'id': '3.366',
    'parent': '2.39',
    'name': '建发国际大厦'
}, {
    'value': 2,
    'id': '3.367',
    'parent': '2.39',
    'name': '文通-财富国际'
}, {
    'value': 1,
    'id': '3.368',
    'parent': '2.39',
    'name': '星外滩10号'
}, {
    'value': 8,
    'id': '3.369',
    'parent': '2.39',
    'name': '海上海'
}, {
    'value': 2,
    'id': '3.370',
    'parent': '2.39',
    'name': '海泰大厦'
}, {
    'value': 2,
    'id': '3.371',
    'parent': '2.39',
    'name': '滨江国际广场'
}, {
    'value': 1,
    'id': '3.372',
    'parent': '2.39',
    'name': '绿地滨江中央广场'
}, {
    'value': 3,
    'id': '3.373',
    'parent': '2.39',
    'name': '郡江国际大厦'
}, {
    'value': 3,
    'id': '3.374',
    'parent': '2.40',
    'name': '信息技术大厦'
}, {
    'value': 2,
    'id': '3.375',
    'parent': '2.40',
    'name': '北美广场'
}, {
    'value': 1,
    'id': '3.376',
    'parent': '2.40',
    'name': '同济联合广场C座'
}, {
    'value': 1,
    'id': '3.377',
    'parent': '2.40',
    'name': '智慧树创意园'
}, {
    'value': 1,
    'id': '3.378',
    'parent': '2.41',
    'name': '133世界广场'
}, {
    'value': 9,
    'id': '3.379',
    'parent': '2.41',
    'name': '上海星汇广场'
}, {
    'value': 2,
    'id': '3.380',
    'parent': '2.41',
    'name': '嘉誉国际广场'
}, {
    'value': 9,
    'id': '3.381',
    'parent': '2.41',
    'name': '湾谷科技园'
}, {
    'value': 4,
    'id': '3.382',
    'parent': '2.41',
    'name': '绿地新江湾大厦'
}, {
    'value': 1,
    'id': '3.383',
    'parent': '2.42',
    'name': '五环大厦'
}, {
    'value': 1,
    'id': '3.384',
    'parent': '2.42',
    'name': '同叶大厦'
}, {
    'value': 2,
    'id': '3.385',
    'parent': '2.42',
    'name': '同济联合广场'
}, {
    'value': 2,
    'id': '3.386',
    'parent': '2.42',
    'name': '杨浦商城'
}, {
    'value': 1,
    'id': '3.387',
    'parent': '2.42',
    'name': '贵人大厦'
}, {
    'value': 1,
    'id': '3.388',
    'parent': '2.43',
    'name': '上海国际设计中心'
}, {
    'value': 1,
    'id': '3.389',
    'parent': '2.43',
    'name': '中通大厦'
}, {
    'value': 2,
    'id': '3.390',
    'parent': '2.43',
    'name': '新纪元国际广场'
}, {
    'value': 1,
    'id': '3.391',
    'parent': '2.43',
    'name': '星汇广场'
}, {
    'value': 1,
    'id': '3.392',
    'parent': '2.43',
    'name': '海上硕和城'
}, {
    'value': 1,
    'id': '3.393',
    'parent': '2.43',
    'name': '白玉兰环保广场'
}, {
    'value': 1,
    'id': '3.394',
    'parent': '2.44',
    'name': '嘉南红塔商务广场'
}, {
    'value': 1,
    'id': '3.395',
    'parent': '2.44',
    'name': '恒耀广场'
}, {
    'value': 3,
    'id': '3.396',
    'parent': '2.44',
    'name': '松江漕河泾'
}, {
    'value': 1,
    'id': '3.397',
    'parent': '2.45',
    'name': '三迪曼哈顿'
}, {
    'value': 1,
    'id': '3.398',
    'parent': '2.45',
    'name': '上海国际中小企业城'
}, {
    'value': 1,
    'id': '3.399',
    'parent': '2.45',
    'name': '中展瑞景'
}, {
    'value': 1,
    'id': '3.400',
    'parent': '2.45',
    'name': '双高世贸广场'
}, {
    'value': 4,
    'id': '3.401',
    'parent': '2.45',
    'name': '嘉立国际广场'
}, {
    'value': 1,
    'id': '3.402',
    'parent': '2.45',
    'name': '平高世贸中心'
}, {
    'value': 1,
    'id': '3.403',
    'parent': '2.45',
    'name': '平高大厦'
}, {
    'value': 1,
    'id': '3.404',
    'parent': '2.45',
    'name': '星辰大厦'
}, {
    'value': 1,
    'id': '3.405',
    'parent': '2.45',
    'name': '松江万达广场'
}, {
    'value': 7,
    'id': '3.406',
    'parent': '2.45',
    'name': '绿亮松江科创园'
}, {
    'value': 3,
    'id': '3.407',
    'parent': '2.46',
    'name': '前滩世贸中心'
}, {
    'value': 3,
    'id': '3.408',
    'parent': '2.46',
    'name': '晶耀前滩'
}, {
    'value': 4,
    'id': '3.409',
    'parent': '2.46',
    'name': '森宏旗臻'
}, {
    'value': 1,
    'id': '3.410',
    'parent': '2.46',
    'name': '比乐创意办公空间'
}, {
    'value': 1,
    'id': '3.411',
    'parent': '2.47',
    'name': '三林金融众创空间'
}, {
    'value': 1,
    'id': '3.412',
    'parent': '2.47',
    'name': '世博办公楼'
}, {
    'value': 1,
    'id': '3.413',
    'parent': '2.47',
    'name': '东方金融园'
}, {
    'value': 1,
    'id': '3.414',
    'parent': '2.47',
    'name': '前滩尚博创意产业园'
}, {
    'value': 1,
    'id': '3.415',
    'parent': '2.47',
    'name': '城建大厦'
}, {
    'value': 1,
    'id': '3.416',
    'parent': '2.47',
    'name': '森宏旗臻二期'
}, {
    'value': 1,
    'id': '3.417',
    'parent': '2.47',
    'name': '环球都会广场'
}, {
    'value': 1,
    'id': '3.418',
    'parent': '2.47',
    'name': '长青企业广场'
}, {
    'value': 3,
    'id': '3.419',
    'parent': '2.48',
    'name': '上海华电大厦'
}, {
    'value': 2,
    'id': '3.420',
    'parent': '2.48',
    'name': '上海意大利中心'
}, {
    'value': 1,
    'id': '3.421',
    'parent': '2.48',
    'name': '世博宝钢大厦'
}, {
    'value': 2,
    'id': '3.422',
    'parent': '2.48',
    'name': '鲁能国际大厦'
}, {
    'value': 2,
    'id': '3.423',
    'parent': '2.49',
    'name': '333世纪大厦'
}, {
    'value': 1,
    'id': '3.424',
    'parent': '2.49',
    'name': '丁香国际大厦'
}, {
    'value': 2,
    'id': '3.425',
    'parent': '2.49',
    'name': '富荟商业广场（写字楼）'
}, {
    'value': 1,
    'id': '3.426',
    'parent': '2.49',
    'name': '巨洋大厦'
}, {
    'value': 4,
    'id': '3.427',
    'parent': '2.49',
    'name': '建工大唐国际大厦'
}, {
    'value': 1,
    'id': '3.428',
    'parent': '2.49',
    'name': '正大喜马拉雅中心'
}, {
    'value': 3,
    'id': '3.429',
    'parent': '2.49',
    'name': '浦东嘉里城'
}, {
    'value': 1,
    'id': '3.430',
    'parent': '2.49',
    'name': '海东大厦'
}, {
    'value': 5,
    'id': '3.431',
    'parent': '2.49',
    'name': '界龙总部园'
}, {
    'value': 3,
    'id': '3.432',
    'parent': '2.49',
    'name': '芳华德必运动LOFT'
}, {
    'value': 1,
    'id': '3.433',
    'parent': '2.49',
    'name': '证大五道口大厦'
}, {
    'value': 1,
    'id': '3.434',
    'parent': '2.49',
    'name': '证大立方大厦'
}, {
    'value': 6,
    'id': '3.435',
    'parent': '2.49',
    'name': '金鹰大厦'
}, {
    'value': 1,
    'id': '3.436',
    'parent': '2.49',
    'name': '青慧谷'
}, {
    'value': 4,
    'id': '3.437',
    'parent': '2.50',
    'name': '上海湾鄂尔多斯大厦'
}, {
    'value': 10,
    'id': '3.438',
    'parent': '2.50',
    'name': '世界广场'
}, {
    'value': 2,
    'id': '3.439',
    'parent': '2.50',
    'name': '东方金融广场'
}, {
    'value': 10,
    'id': '3.440',
    'parent': '2.50',
    'name': '中融国际商城'
}, {
    'value': 13,
    'id': '3.441',
    'parent': '2.50',
    'name': '中融恒瑞国际大厦'
}, {
    'value': 5,
    'id': '3.442',
    'parent': '2.50',
    'name': '乐凯大厦'
}, {
    'value': 1,
    'id': '3.443',
    'parent': '2.50',
    'name': '众城大厦'
}, {
    'value': 3,
    'id': '3.444',
    'parent': '2.50',
    'name': '华润时代广场'
}, {
    'value': 3,
    'id': '3.445',
    'parent': '2.50',
    'name': '华融大厦'
}, {
    'value': 4,
    'id': '3.446',
    'parent': '2.50',
    'name': '宝安大厦'
}, {
    'value': 4,
    'id': '3.447',
    'parent': '2.50',
    'name': '德必梅园WE'
}, {
    'value': 7,
    'id': '3.448',
    'parent': '2.50',
    'name': '新梅联合广场'
}, {
    'value': 2,
    'id': '3.449',
    'parent': '2.50',
    'name': '汤臣中心'
}, {
    'value': 12,
    'id': '3.450',
    'parent': '2.50',
    'name': '汤臣金融大厦'
}, {
    'value': 1,
    'id': '3.451',
    'parent': '2.50',
    'name': '波特营'
}, {
    'value': 9,
    'id': '3.452',
    'parent': '2.50',
    'name': '生命人寿大厦'
}, {
    'value': 2,
    'id': '3.453',
    'parent': '2.50',
    'name': '紫竹国际大厦'
}, {
    'value': 5,
    'id': '3.454',
    'parent': '2.50',
    'name': '胜康廖氏大厦'
}, {
    'value': 2,
    'id': '3.455',
    'parent': '2.50',
    'name': '良友大厦'
}, {
    'value': 2,
    'id': '3.456',
    'parent': '2.50',
    'name': '裕安大厦'
}, {
    'value': 3,
    'id': '3.457',
    'parent': '2.50',
    'name': '远东大厦'
}, {
    'value': 1,
    'id': '3.458',
    'parent': '2.50',
    'name': '金穗大厦'
}, {
    'value': 1,
    'id': '3.459',
    'parent': '2.50',
    'name': '隆宇大厦'
}, {
    'value': 2,
    'id': '3.460',
    'parent': '2.51',
    'name': '东方尚博创意园'
}, {
    'value': 8,
    'id': '3.461',
    'parent': '2.51',
    'name': '中建时代广场'
}, {
    'value': 3,
    'id': '3.462',
    'parent': '2.51',
    'name': '兰村大厦'
}, {
    'value': 2,
    'id': '3.463',
    'parent': '2.51',
    'name': '加禾LOFT创意园'
}, {
    'value': 1,
    'id': '3.464',
    'parent': '2.51',
    'name': '华南大厦'
}, {
    'value': 1,
    'id': '3.465',
    'parent': '2.51',
    'name': '华晔创意园'
}, {
    'value': 1,
    'id': '3.466',
    'parent': '2.51',
    'name': '天安万科御河企业公馆'
}, {
    'value': 1,
    'id': '3.467',
    'parent': '2.51',
    'name': '左岸88'
}, {
    'value': 1,
    'id': '3.468',
    'parent': '2.51',
    'name': '御河企业公馆'
}, {
    'value': 1,
    'id': '3.469',
    'parent': '2.51',
    'name': '振华企业广场'
}, {
    'value': 1,
    'id': '3.470',
    'parent': '2.51',
    'name': '歆翱商务楼'
}, {
    'value': 1,
    'id': '3.471',
    'parent': '2.51',
    'name': '永旭商务中心'
}, {
    'value': 3,
    'id': '3.472',
    'parent': '2.51',
    'name': '海富花园'
}, {
    'value': 1,
    'id': '3.473',
    'parent': '2.52',
    'name': '医谷・现代商务园'
}, {
    'value': 1,
    'id': '3.474',
    'parent': '2.53',
    'name': '中国石化物资大厦'
}, {
    'value': 2,
    'id': '3.475',
    'parent': '2.53',
    'name': '交能大厦'
}, {
    'value': 1,
    'id': '3.476',
    'parent': '2.53',
    'name': '众原企业天地'
}, {
    'value': 1,
    'id': '3.477',
    'parent': '2.53',
    'name': '众原国际中心'
}, {
    'value': 1,
    'id': '3.478',
    'parent': '2.53',
    'name': '外高桥酒类展示交易中心'
}, {
    'value': 1,
    'id': '3.479',
    'parent': '2.53',
    'name': '晓富金融大厦'
}, {
    'value': 1,
    'id': '3.480',
    'parent': '2.53',
    'name': '诚信国际大厦'
}, {
    'value': 1,
    'id': '3.481',
    'parent': '2.53',
    'name': '高华大楼'
}, {
    'value': 2,
    'id': '3.482',
    'parent': '2.54',
    'name': '交能国际大厦'
}, {
    'value': 1,
    'id': '3.483',
    'parent': '2.55',
    'name': '绿地东海岸国际广场'
}, {
    'value': 1,
    'id': '3.484',
    'parent': '2.56',
    'name': 'iDream张江公馆'
}, {
    'value': 5,
    'id': '3.485',
    'parent': '2.56',
    'name': '上海世和商务中心'
}, {
    'value': 4,
    'id': '3.486',
    'parent': '2.56',
    'name': '上海开文大厦'
}, {
    'value': 6,
    'id': '3.487',
    'parent': '2.56',
    'name': '世和中心'
}, {
    'value': 1,
    'id': '3.488',
    'parent': '2.56',
    'name': '中兴上海智慧园'
}, {
    'value': 2,
    'id': '3.489',
    'parent': '2.56',
    'name': '亚芯中心'
}, {
    'value': 1,
    'id': '3.490',
    'parent': '2.56',
    'name': '凌阳大楼'
}, {
    'value': 1,
    'id': '3.491',
    'parent': '2.56',
    'name': '凯瑞大厦'
}, {
    'value': 16,
    'id': '3.492',
    'parent': '2.56',
    'name': '创企天地产业园'
}, {
    'value': 3,
    'id': '3.493',
    'parent': '2.56',
    'name': '创智空间'
}, {
    'value': 5,
    'id': '3.494',
    'parent': '2.56',
    'name': '创智良仓'
}, {
    'value': 2,
    'id': '3.495',
    'parent': '2.56',
    'name': '创研智造'
}, {
    'value': 2,
    'id': '3.496',
    'parent': '2.56',
    'name': '华强科技大厦'
}, {
    'value': 2,
    'id': '3.497',
    'parent': '2.56',
    'name': '博达科技楼'
}, {
    'value': 1,
    'id': '3.498',
    'parent': '2.56',
    'name': '圣御大厦'
}, {
    'value': 2,
    'id': '3.499',
    'parent': '2.56',
    'name': '富海商务苑'
}, {
    'value': 7,
    'id': '3.500',
    'parent': '2.56',
    'name': '展想广场'
}, {
    'value': 1,
    'id': '3.501',
    'parent': '2.56',
    'name': '展讯中心'
}, {
    'value': 3,
    'id': '3.502',
    'parent': '2.56',
    'name': '康拜丝'
}, {
    'value': 1,
    'id': '3.503',
    'parent': '2.56',
    'name': '张江.华鑫慧天地'
}, {
    'value': 5,
    'id': '3.504',
    'parent': '2.56',
    'name': '张江·矽岸国际'
}, {
    'value': 1,
    'id': '3.505',
    'parent': '2.56',
    'name': '张江创新园'
}, {
    'value': 8,
    'id': '3.506',
    'parent': '2.56',
    'name': '张江国创中心'
}, {
    'value': 3,
    'id': '3.507',
    'parent': '2.56',
    'name': '张江微电子港'
}, {
    'value': 1,
    'id': '3.508',
    'parent': '2.56',
    'name': '张江春申大厦'
}, {
    'value': 1,
    'id': '3.509',
    'parent': '2.56',
    'name': '张江润和国际总部园'
}, {
    'value': 2,
    'id': '3.510',
    'parent': '2.56',
    'name': '张江集电港'
}, {
    'value': 1,
    'id': '3.511',
    'parent': '2.56',
    'name': '德国中心'
}, {
    'value': 1,
    'id': '3.512',
    'parent': '2.56',
    'name': '恒越大厦'
}, {
    'value': 2,
    'id': '3.513',
    'parent': '2.56',
    'name': '惠生中心'
}, {
    'value': 5,
    'id': '3.514',
    'parent': '2.56',
    'name': '日月光集团'
}, {
    'value': 3,
    'id': '3.515',
    'parent': '2.56',
    'name': '星创科技广场'
}, {
    'value': 4,
    'id': '3.516',
    'parent': '2.56',
    'name': '星峰企业园'
}, {
    'value': 3,
    'id': '3.517',
    'parent': '2.56',
    'name': '浦东张江软件园'
}, {
    'value': 1,
    'id': '3.518',
    'parent': '2.56',
    'name': '漕河泾康桥商务绿洲'
}, {
    'value': 6,
    'id': '3.519',
    'parent': '2.56',
    'name': '盛大全球研发中心'
}, {
    'value': 8,
    'id': '3.520',
    'parent': '2.56',
    'name': '盛大天地源创谷'
}, {
    'value': 4,
    'id': '3.521',
    'parent': '2.56',
    'name': '盛大天地青春里2.0'
}, {
    'value': 1,
    'id': '3.522',
    'parent': '2.56',
    'name': '科技领袖之都'
}, {
    'value': 4,
    'id': '3.523',
    'parent': '2.56',
    'name': '科海大楼'
}, {
    'value': 2,
    'id': '3.524',
    'parent': '2.56',
    'name': '科苑大楼'
}, {
    'value': 1,
    'id': '3.525',
    'parent': '2.56',
    'name': '稻盛科研楼'
}, {
    'value': 8,
    'id': '3.526',
    'parent': '2.56',
    'name': '绿地M-TOWN'
}, {
    'value': 1,
    'id': '3.527',
    'parent': '2.56',
    'name': '金蝶软件园'
}, {
    'value': 3,
    'id': '3.528',
    'parent': '2.56',
    'name': '锦科文化产业园'
}, {
    'value': 3,
    'id': '3.529',
    'parent': '2.56',
    'name': '长泰广场'
}, {
    'value': 3,
    'id': '3.530',
    'parent': '2.56',
    'name': '集创公园'
}, {
    'value': 2,
    'id': '3.531',
    'parent': '2.57',
    'name': 'BHC中环中心'
}, {
    'value': 1,
    'id': '3.532',
    'parent': '2.57',
    'name': '万科活力城'
}, {
    'value': 2,
    'id': '3.533',
    'parent': '2.57',
    'name': '上海中天科技商务园'
}, {
    'value': 1,
    'id': '3.534',
    'parent': '2.57',
    'name': '上海总部湾'
}, {
    'value': 1,
    'id': '3.535',
    'parent': '2.57',
    'name': '仕方广场'
}, {
    'value': 3,
    'id': '3.536',
    'parent': '2.57',
    'name': '沃力创业园'
}, {
    'value': 4,
    'id': '3.537',
    'parent': '2.58',
    'name': '中港汇.浦东'
}, {
    'value': 2,
    'id': '3.538',
    'parent': '2.58',
    'name': '天物空间'
}, {
    'value': 3,
    'id': '3.539',
    'parent': '2.58',
    'name': '置汇旭辉广场'
}, {
    'value': 5,
    'id': '3.540',
    'parent': '2.59',
    'name': 'soho世纪广场'
}, {
    'value': 2,
    'id': '3.541',
    'parent': '2.59',
    'name': '一佰杉杉大厦'
}, {
    'value': 1,
    'id': '3.542',
    'parent': '2.59',
    'name': '东方国际科技大厦'
}, {
    'value': 3,
    'id': '3.543',
    'parent': '2.59',
    'name': '东方大厦'
}, {
    'value': 1,
    'id': '3.544',
    'parent': '2.59',
    'name': '东方希望大厦'
}, {
    'value': 1,
    'id': '3.545',
    'parent': '2.59',
    'name': '中国煤炭大厦'
}, {
    'value': 2,
    'id': '3.546',
    'parent': '2.59',
    'name': '中建大厦'
}, {
    'value': 1,
    'id': '3.547',
    'parent': '2.59',
    'name': '中达广场'
}, {
    'value': 1,
    'id': '3.548',
    'parent': '2.59',
    'name': '全华信息大楼'
}, {
    'value': 3,
    'id': '3.549',
    'parent': '2.59',
    'name': '双鸽大厦'
}, {
    'value': 2,
    'id': '3.550',
    'parent': '2.59',
    'name': '同盛大厦'
}, {
    'value': 1,
    'id': '3.551',
    'parent': '2.59',
    'name': '嘉兴大厦'
}, {
    'value': 1,
    'id': '3.552',
    'parent': '2.59',
    'name': '国际金融家'
}, {
    'value': 1,
    'id': '3.553',
    'parent': '2.59',
    'name': '宝钢大厦'
}, {
    'value': 3,
    'id': '3.554',
    'parent': '2.59',
    'name': '新天国际大厦'
}, {
    'value': 1,
    'id': '3.555',
    'parent': '2.59',
    'name': '浦项商务广场'
}, {
    'value': 2,
    'id': '3.556',
    'parent': '2.59',
    'name': '由由世纪广场'
}, {
    'value': 2,
    'id': '3.557',
    'parent': '2.59',
    'name': '由由燕乔大厦'
}, {
    'value': 3,
    'id': '3.558',
    'parent': '2.59',
    'name': '葛洲坝大厦'
}, {
    'value': 7,
    'id': '3.559',
    'parent': '2.59',
    'name': '钱江大厦'
}, {
    'value': 4,
    'id': '3.560',
    'parent': '2.59',
    'name': '长泰国际金融大厦'
}, {
    'value': 3,
    'id': '3.561',
    'parent': '2.59',
    'name': '陆家嘴商务广场'
}, {
    'value': 1,
    'id': '3.562',
    'parent': '2.59',
    'name': '陆家嘴基金大厦'
}, {
    'value': 1,
    'id': '3.563',
    'parent': '2.60',
    'name': '一百杉杉大厦'
}, {
    'value': 6,
    'id': '3.564',
    'parent': '2.61',
    'name': '东方万国企业中心'
}, {
    'value': 3,
    'id': '3.565',
    'parent': '2.61',
    'name': '中新传媒大厦'
}, {
    'value': 2,
    'id': '3.566',
    'parent': '2.61',
    'name': '中环滨江大厦'
}, {
    'value': 2,
    'id': '3.567',
    'parent': '2.61',
    'name': '凯龙金领大厦'
}, {
    'value': 4,
    'id': '3.568',
    'parent': '2.61',
    'name': '华虹创新'
}, {
    'value': 3,
    'id': '3.569',
    'parent': '2.61',
    'name': '宏南投资大厦'
}, {
    'value': 3,
    'id': '3.570',
    'parent': '2.61',
    'name': '方正大厦'
}, {
    'value': 1,
    'id': '3.571',
    'parent': '2.61',
    'name': '梵克雅堡'
}, {
    'value': 1,
    'id': '3.572',
    'parent': '2.61',
    'name': '现代通信大厦'
}, {
    'value': 1,
    'id': '3.573',
    'parent': '2.61',
    'name': '由度工场'
}, {
    'value': 2,
    'id': '3.574',
    'parent': '2.61',
    'name': '碧云公馆'
}, {
    'value': 2,
    'id': '3.575',
    'parent': '2.61',
    'name': '碧海现代苑'
}, {
    'value': 2,
    'id': '3.576',
    'parent': '2.61',
    'name': '福建天安大厦'
}, {
    'value': 1,
    'id': '3.577',
    'parent': '2.61',
    'name': '禹洲广场'
}, {
    'value': 2,
    'id': '3.578',
    'parent': '2.61',
    'name': '禹洲金桥国际一期'
}, {
    'value': 1,
    'id': '3.579',
    'parent': '2.61',
    'name': '禹洲金桥国际三期'
}, {
    'value': 1,
    'id': '3.580',
    'parent': '2.61',
    'name': '禹洲金桥国际二期'
}, {
    'value': 1,
    'id': '3.581',
    'parent': '2.61',
    'name': '禹洲金桥国际五期'
}, {
    'value': 2,
    'id': '3.582',
    'parent': '2.61',
    'name': '联创国际'
}, {
    'value': 1,
    'id': '3.583',
    'parent': '2.61',
    'name': '金桥数研基地'
}, {
    'value': 1,
    'id': '3.584',
    'parent': '2.61',
    'name': '金桥瑞邑'
}, {
    'value': 11,
    'id': '3.585',
    'parent': '2.61',
    'name': '金领之都'
}, {
    'value': 1,
    'id': '3.586',
    'parent': '2.61',
    'name': '金领之都B区'
}, {
    'value': 1,
    'id': '3.587',
    'parent': '2.61',
    'name': '鑫桥创意园'
}, {
    'value': 1,
    'id': '3.588',
    'parent': '2.61',
    'name': '银桥大厦'
}, {
    'value': 3,
    'id': '3.589',
    'parent': '2.61',
    'name': '锦绣申江'
}, {
    'value': 3,
    'id': '3.590',
    'parent': '2.62',
    'name': '21世纪中心大厦'
}, {
    'value': 11,
    'id': '3.591',
    'parent': '2.62',
    'name': '上海中心'
}, {
    'value': 2,
    'id': '3.592',
    'parent': '2.62',
    'name': '上海保利广场'
}, {
    'value': 7,
    'id': '3.593',
    'parent': '2.62',
    'name': '上海银行大厦'
}, {
    'value': 1,
    'id': '3.594',
    'parent': '2.62',
    'name': '世纪大都会'
}, {
    'value': 8,
    'id': '3.595',
    'parent': '2.62',
    'name': '世纪汇广场'
}, {
    'value': 3,
    'id': '3.596',
    'parent': '2.62',
    'name': '东亚银行金融大厦'
}, {
    'value': 1,
    'id': '3.597',
    'parent': '2.62',
    'name': '东方汇经OFC'
}, {
    'value': 21,
    'id': '3.598',
    'parent': '2.62',
    'name': '中国人寿金融中心'
}, {
    'value': 1,
    'id': '3.599',
    'parent': '2.62',
    'name': '中国华电'
}, {
    'value': 1,
    'id': '3.600',
    'parent': '2.62',
    'name': '中国船舶大厦'
}, {
    'value': 8,
    'id': '3.601',
    'parent': '2.62',
    'name': '中融碧玉蓝天'
}, {
    'value': 1,
    'id': '3.602',
    'parent': '2.62',
    'name': '中银大厦'
}, {
    'value': 4,
    'id': '3.603',
    'parent': '2.62',
    'name': '华夏银行大厦'
}, {
    'value': 4,
    'id': '3.604',
    'parent': '2.62',
    'name': '华能联合大厦'
}, {
    'value': 1,
    'id': '3.605',
    'parent': '2.62',
    'name': '国家开发银行大厦'
}, {
    'value': 6,
    'id': '3.606',
    'parent': '2.62',
    'name': '国金中心'
}, {
    'value': 1,
    'id': '3.607',
    'parent': '2.62',
    'name': '国际航运金融大厦'
}, {
    'value': 4,
    'id': '3.608',
    'parent': '2.62',
    'name': '太平金融大厦'
}, {
    'value': 5,
    'id': '3.609',
    'parent': '2.62',
    'name': '宏嘉大厦'
}, {
    'value': 2,
    'id': '3.610',
    'parent': '2.62',
    'name': '建工大厦'
}, {
    'value': 6,
    'id': '3.611',
    'parent': '2.62',
    'name': '招商局大厦'
}, {
    'value': 7,
    'id': '3.612',
    'parent': '2.62',
    'name': '斯米克大厦'
}, {
    'value': 11,
    'id': '3.613',
    'parent': '2.62',
    'name': '新上海国际大厦'
}, {
    'value': 2,
    'id': '3.614',
    'parent': '2.62',
    'name': '时代金融中心'
}, {
    'value': 6,
    'id': '3.615',
    'parent': '2.62',
    'name': '未来资产大厦'
}, {
    'value': 1,
    'id': '3.616',
    'parent': '2.62',
    'name': '永华大厦'
}, {
    'value': 2,
    'id': '3.617',
    'parent': '2.62',
    'name': '汇亚大厦'
}, {
    'value': 1,
    'id': '3.618',
    'parent': '2.62',
    'name': '浦发大厦'
}, {
    'value': 1,
    'id': '3.619',
    'parent': '2.62',
    'name': '港务大厦'
}, {
    'value': 3,
    'id': '3.620',
    'parent': '2.62',
    'name': '滨江万科中心'
}, {
    'value': 2,
    'id': '3.621',
    'parent': '2.62',
    'name': '环球金融中心'
}, {
    'value': 5,
    'id': '3.622',
    'parent': '2.62',
    'name': '花旗集团大厦'
}, {
    'value': 5,
    'id': '3.623',
    'parent': '2.62',
    'name': '融汇958创意园'
}, {
    'value': 2,
    'id': '3.624',
    'parent': '2.62',
    'name': '裕景国际商务广场A座'
}, {
    'value': 1,
    'id': '3.625',
    'parent': '2.62',
    'name': '裕景国际商务广场B座'
}, {
    'value': 4,
    'id': '3.626',
    'parent': '2.62',
    'name': '裕景国际大厦'
}, {
    'value': 12,
    'id': '3.627',
    'parent': '2.62',
    'name': '金茂大厦'
}, {
    'value': 3,
    'id': '3.628',
    'parent': '2.62',
    'name': '陆家嘴软件园'
}, {
    'value': 1,
    'id': '3.629',
    'parent': '2.62',
    'name': '陆家嘴钻石大厦'
}, {
    'value': 2,
    'id': '3.630',
    'parent': '2.62',
    'name': '震旦国际大楼'
}, {
    'value': 1,
    'id': '3.631',
    'parent': '2.63',
    'name': '1930鑫鑫创意园'
}, {
    'value': 2,
    'id': '3.632',
    'parent': '2.63',
    'name': '创富大厦'
}, {
    'value': 1,
    'id': '3.633',
    'parent': '2.63',
    'name': '岳洋大厦'
}, {
    'value': 1,
    'id': '3.634',
    'parent': '2.63',
    'name': '飘鹰世纪大厦'
}, {
    'value': 3,
    'id': '3.635',
    'parent': '2.63',
    'name': '骏丰国际财富广场'
}, {
    'value': 1,
    'id': '3.636',
    'parent': '2.64',
    'name': '凯德龙之梦虹口广场'
}, {
    'value': 1,
    'id': '3.637',
    'parent': '2.64',
    'name': '嘉和国际大厦'
}, {
    'value': 1,
    'id': '3.638',
    'parent': '2.64',
    'name': '法兰桥创意园'
}, {
    'value': 2,
    'id': '3.639',
    'parent': '2.64',
    'name': '绿亮虹口科创园'
}, {
    'value': 4,
    'id': '3.640',
    'parent': '2.64',
    'name': '花园坊上海节能环保中心'
}, {
    'value': 1,
    'id': '3.641',
    'parent': '2.64',
    'name': '虹口图书馆写字楼'
}, {
    'value': 5,
    'id': '3.642',
    'parent': '2.64',
    'name': '运动Loft'
}, {
    'value': 2,
    'id': '3.643',
    'parent': '2.65',
    'name': '上海滩国际大厦'
}, {
    'value': 1,
    'id': '3.644',
    'parent': '2.65',
    'name': '东方海港国际大厦'
}, {
    'value': 1,
    'id': '3.645',
    'parent': '2.65',
    'name': '中房长治大楼'
}, {
    'value': 1,
    'id': '3.646',
    'parent': '2.65',
    'name': '中科招商.国际财富中心'
}, {
    'value': 11,
    'id': '3.647',
    'parent': '2.65',
    'name': '北外滩金光中心'
}, {
    'value': 1,
    'id': '3.648',
    'parent': '2.65',
    'name': '印坊创意园'
}, {
    'value': 4,
    'id': '3.649',
    'parent': '2.65',
    'name': '合生财富大厦'
}, {
    'value': 1,
    'id': '3.650',
    'parent': '2.65',
    'name': '国际港务大厦'
}, {
    'value': 1,
    'id': '3.651',
    'parent': '2.65',
    'name': '城投控股大厦'
}, {
    'value': 2,
    'id': '3.652',
    'parent': '2.65',
    'name': '外滩588'
}, {
    'value': 5,
    'id': '3.653',
    'parent': '2.65',
    'name': '宝矿国际大厦'
}, {
    'value': 1,
    'id': '3.654',
    'parent': '2.65',
    'name': '家化金融大厦'
}, {
    'value': 2,
    'id': '3.655',
    'parent': '2.65',
    'name': '新华保险大厦'
}, {
    'value': 8,
    'id': '3.656',
    'parent': '2.65',
    'name': '星荟中心'
}, {
    'value': 2,
    'id': '3.657',
    'parent': '2.65',
    'name': '森林湾大厦'
}, {
    'value': 1,
    'id': '3.658',
    'parent': '2.65',
    'name': '永融企业中心'
}, {
    'value': 4,
    'id': '3.659',
    'parent': '2.65',
    'name': '浦江国际金融广场'
}, {
    'value': 4,
    'id': '3.660',
    'parent': '2.65',
    'name': '瑞丰国际大厦'
}, {
    'value': 5,
    'id': '3.661',
    'parent': '2.65',
    'name': '白金湾广场'
}, {
    'value': 1,
    'id': '3.662',
    'parent': '2.65',
    'name': '绿地北外滩中心'
}, {
    'value': 1,
    'id': '3.663',
    'parent': '2.65',
    'name': '耀江国际大厦'
}, {
    'value': 4,
    'id': '3.664',
    'parent': '2.65',
    'name': '耀江国际广场'
}, {
    'value': 5,
    'id': '3.665',
    'parent': '2.65',
    'name': '虹口SOHO'
}, {
    'value': 2,
    'id': '3.666',
    'parent': '2.65',
    'name': '虹口绿亮科创园'
}, {
    'value': 7,
    'id': '3.667',
    'parent': '2.65',
    'name': '金融街海伦中心'
}, {
    'value': 1,
    'id': '3.668',
    'parent': '2.65',
    'name': '高阳商务中心'
}, {
    'value': 1,
    'id': '3.669',
    'parent': '2.66',
    'name': '金岸大厦'
}, {
    'value': 1,
    'id': '3.670',
    'parent': '2.67',
    'name': '上海利通广场'
}, {
    'value': 1,
    'id': '3.671',
    'parent': '2.67',
    'name': '上海国际商厦'
}, {
    'value': 10,
    'id': '3.672',
    'parent': '2.67',
    'name': '中信广场'
}, {
    'value': 1,
    'id': '3.673',
    'parent': '2.67',
    'name': '华虹国际大厦'
}, {
    'value': 1,
    'id': '3.674',
    'parent': '2.67',
    'name': '国际商厦'
}, {
    'value': 4,
    'id': '3.675',
    'parent': '2.67',
    'name': '壹丰广场'
}, {
    'value': 1,
    'id': '3.676',
    'parent': '2.67',
    'name': '方舟大厦'
}, {
    'value': 1,
    'id': '3.677',
    'parent': '2.67',
    'name': '明凯大厦'
}, {
    'value': 3,
    'id': '3.678',
    'parent': '2.67',
    'name': '海泰国际大厦'
}, {
    'value': 1,
    'id': '3.679',
    'parent': '2.67',
    'name': '海泰时代大厦'
}, {
    'value': 3,
    'id': '3.680',
    'parent': '2.67',
    'name': '爱家国际大厦'
}, {
    'value': 1,
    'id': '3.681',
    'parent': '2.67',
    'name': '盛邦国际大厦'
}, {
    'value': 1,
    'id': '3.682',
    'parent': '2.67',
    'name': '福德商务中心'
}, {
    'value': 6,
    'id': '3.683',
    'parent': '2.67',
    'name': '绿地创客'
}, {
    'value': 1,
    'id': '3.684',
    'parent': '2.67',
    'name': '荣欣大厦'
}, {
    'value': 2,
    'id': '3.685',
    'parent': '2.67',
    'name': '高宝新时代广场'
}, {
    'value': 1,
    'id': '3.686',
    'parent': '2.68',
    'name': '1933老场坊'
}, {
    'value': 3,
    'id': '3.687',
    'parent': '2.69',
    'name': '1876老站创意园'
}, {
    'value': 1,
    'id': '3.688',
    'parent': '2.69',
    'name': '上海中观产业园'
}, {
    'value': 2,
    'id': '3.689',
    'parent': '2.69',
    'name': '复城国际'
}, {
    'value': 1,
    'id': '3.690',
    'parent': '2.69',
    'name': '宝隆一方大厦'
}, {
    'value': 1,
    'id': '3.691',
    'parent': '2.69',
    'name': '曲阳商务中心'
}, {
    'value': 1,
    'id': '3.692',
    'parent': '2.69',
    'name': '沪办大厦'
}, {
    'value': 1,
    'id': '3.693',
    'parent': '2.70',
    'name': '石油大厦'
}, {
    'value': 2,
    'id': '3.694',
    'parent': '2.71',
    'name': '东华创意园'
}, {
    'value': 1,
    'id': '3.695',
    'parent': '2.71',
    'name': '东华时尚创意园'
}, {
    'value': 1,
    'id': '3.696',
    'parent': '2.71',
    'name': '东风商务园区'
}, {
    'value': 3,
    'id': '3.697',
    'parent': '2.71',
    'name': '兆丰世贸大厦'
}, {
    'value': 7,
    'id': '3.698',
    'parent': '2.71',
    'name': '兆丰广场'
}, {
    'value': 1,
    'id': '3.699',
    'parent': '2.71',
    'name': '凯阳大厦'
}, {
    'value': 8,
    'id': '3.700',
    'parent': '2.71',
    'name': '华宁国际广场'
}, {
    'value': 2,
    'id': '3.701',
    'parent': '2.71',
    'name': '华敏翰尊国际大厦'
}, {
    'value': 4,
    'id': '3.702',
    'parent': '2.71',
    'name': '嘉春753园区'
}, {
    'value': 1,
    'id': '3.703',
    'parent': '2.71',
    'name': '尚街会馆'
}, {
    'value': 2,
    'id': '3.704',
    'parent': '2.71',
    'name': '弘基创邑国际园'
}, {
    'value': 1,
    'id': '3.705',
    'parent': '2.71',
    'name': '易园'
}, {
    'value': 1,
    'id': '3.706',
    'parent': '2.71',
    'name': '江苏路老洋房'
}, {
    'value': 4,
    'id': '3.707',
    'parent': '2.71',
    'name': '绿地商务大厦'
}, {
    'value': 2,
    'id': '3.708',
    'parent': '2.71',
    'name': '绿洲大厦'
}, {
    'value': 2,
    'id': '3.709',
    'parent': '2.71',
    'name': '联通大厦'
}, {
    'value': 1,
    'id': '3.710',
    'parent': '2.71',
    'name': '舜元企业发展大厦A栋'
}, {
    'value': 6,
    'id': '3.711',
    'parent': '2.71',
    'name': '舜元企业发展大厦B栋'
}, {
    'value': 1,
    'id': '3.712',
    'parent': '2.71',
    'name': '花园大厦'
}, {
    'value': 2,
    'id': '3.713',
    'parent': '2.71',
    'name': '虹桥世家花园写字楼'
}, {
    'value': 1,
    'id': '3.714',
    'parent': '2.71',
    'name': '裕丰国际大厦'
}, {
    'value': 7,
    'id': '3.715',
    'parent': '2.71',
    'name': '长宁88中心'
}, {
    'value': 8,
    'id': '3.716',
    'parent': '2.71',
    'name': '长宁来福士广场'
}, {
    'value': 1,
    'id': '3.717',
    'parent': '2.71',
    'name': '龙之梦购物中心'
}, {
    'value': 1,
    'id': '3.718',
    'parent': '2.72',
    'name': '华敏翰尊国际商务大厦'
}, {
    'value': 2,
    'id': '3.719',
    'parent': '2.73',
    'name': '天山大厦'
}, {
    'value': 1,
    'id': '3.720',
    'parent': '2.73',
    'name': '天祥大厦'
}, {
    'value': 1,
    'id': '3.721',
    'parent': '2.73',
    'name': '神州数码科技大厦'
}, {
    'value': 2,
    'id': '3.722',
    'parent': '2.73',
    'name': '虹桥临空工贸小区'
}, {
    'value': 1,
    'id': '3.723',
    'parent': '2.74',
    'name': '东银中心'
}, {
    'value': 1,
    'id': '3.724',
    'parent': '2.74',
    'name': '古北国际财富中心'
}, {
    'value': 1,
    'id': '3.725',
    'parent': '2.74',
    'name': '尼克大厦'
}, {
    'value': 2,
    'id': '3.726',
    'parent': '2.74',
    'name': '尼克大楼'
}, {
    'value': 18,
    'id': '3.727',
    'parent': '2.75',
    'name': 'SOHO天山广场'
}, {
    'value': 1,
    'id': '3.728',
    'parent': '2.75',
    'name': '上服创意园'
}, {
    'value': 3,
    'id': '3.729',
    'parent': '2.75',
    'name': '同达创业'
}, {
    'value': 2,
    'id': '3.730',
    'parent': '2.75',
    'name': '呈远大厦'
}, {
    'value': 1,
    'id': '3.731',
    'parent': '2.75',
    'name': '思创大厦'
}, {
    'value': 2,
    'id': '3.732',
    'parent': '2.75',
    'name': '慧谷白猫科技园'
}, {
    'value': 2,
    'id': '3.733',
    'parent': '2.75',
    'name': '捷运大厦'
}, {
    'value': 2,
    'id': '3.734',
    'parent': '2.75',
    'name': '海益商务大厦'
}, {
    'value': 1,
    'id': '3.735',
    'parent': '2.76',
    'name': '凯利大厦'
}, {
    'value': 10,
    'id': '3.736',
    'parent': '2.76',
    'name': '华敏翰尊国际'
}, {
    'value': 1,
    'id': '3.737',
    'parent': '2.76',
    'name': '华融国际大厦'
}, {
    'value': 2,
    'id': '3.738',
    'parent': '2.76',
    'name': '嘉利大厦'
}, {
    'value': 4,
    'id': '3.739',
    'parent': '2.76',
    'name': '嘉宁国际大厦'
}, {
    'value': 2,
    'id': '3.740',
    'parent': '2.76',
    'name': '圣骊虹桥创意园'
}, {
    'value': 1,
    'id': '3.741',
    'parent': '2.76',
    'name': '大众金融大厦'
}, {
    'value': 1,
    'id': '3.742',
    'parent': '2.76',
    'name': '大吉地世贸大厦'
}, {
    'value': 3,
    'id': '3.743',
    'parent': '2.76',
    'name': '天杉•易园'
}, {
    'value': 2,
    'id': '3.744',
    'parent': '2.76',
    'name': '法华525创意树林'
}, {
    'value': 1,
    'id': '3.745',
    'parent': '2.76',
    'name': '玉嘉大厦'
}, {
    'value': 2,
    'id': '3.746',
    'parent': '2.76',
    'name': '禾森商务中心'
}, {
    'value': 1,
    'id': '3.747',
    'parent': '2.76',
    'name': '红坊'
}, {
    'value': 3,
    'id': '3.748',
    'parent': '2.76',
    'name': '银统大厦'
}, {
    'value': 1,
    'id': '3.749',
    'parent': '2.76',
    'name': '长峰中心.聚贤阁'
}, {
    'value': 2,
    'id': '3.750',
    'parent': '2.76',
    'name': '首信银都国际广场'
}, {
    'value': 1,
    'id': '3.751',
    'parent': '2.76',
    'name': '龙之梦大厦'
}, {
    'value': 1,
    'id': '3.752',
    'parent': '2.76',
    'name': '龙峰大厦'
}, {
    'value': 3,
    'id': '3.753',
    'parent': '2.77',
    'name': '东华大学科技园'
}, {
    'value': 9,
    'id': '3.754',
    'parent': '2.77',
    'name': '凌空SOHO'
}, {
    'value': 1,
    'id': '3.755',
    'parent': '2.77',
    'name': '尚品都汇'
}, {
    'value': 7,
    'id': '3.756',
    'parent': '2.77',
    'name': '建滔企业广场'
}, {
    'value': 7,
    'id': '3.757',
    'parent': '2.77',
    'name': '扬子江企业国际广场'
}, {
    'value': 1,
    'id': '3.758',
    'parent': '2.77',
    'name': '旭辉虹桥国际'
}, {
    'value': 1,
    'id': '3.759',
    'parent': '2.77',
    'name': '明基广场'
}, {
    'value': 5,
    'id': '3.760',
    'parent': '2.77',
    'name': '汤泉国际'
}, {
    'value': 7,
    'id': '3.761',
    'parent': '2.77',
    'name': '统一企业大厦'
}, {
    'value': 1,
    'id': '3.762',
    'parent': '2.77',
    'name': '虹桥国际商务花园'
}, {
    'value': 2,
    'id': '3.763',
    'parent': '2.77',
    'name': '虹桥国际科技广场'
}, {
    'value': 2,
    'id': '3.764',
    'parent': '2.77',
    'name': '鑫达商务楼'
}, {
    'value': 8,
    'id': '3.765',
    'parent': '2.78',
    'name': 'SOHO中山广场'
}, {
    'value': 5,
    'id': '3.766',
    'parent': '2.78',
    'name': '上海万都中心大厦'
}, {
    'value': 4,
    'id': '3.767',
    'parent': '2.78',
    'name': '世贸商城'
}, {
    'value': 1,
    'id': '3.768',
    'parent': '2.78',
    'name': '东方国际大厦'
}, {
    'value': 3,
    'id': '3.769',
    'parent': '2.78',
    'name': '东方维京大厦'
}, {
    'value': 1,
    'id': '3.770',
    'parent': '2.78',
    'name': '中关村虹桥创新中心'
}, {
    'value': 2,
    'id': '3.771',
    'parent': '2.78',
    'name': '中山万博国际中心'
}, {
    'value': 2,
    'id': '3.772',
    'parent': '2.78',
    'name': '仲盛金融中心'
}, {
    'value': 7,
    'id': '3.773',
    'parent': '2.78',
    'name': '华闻国际大厦'
}, {
    'value': 1,
    'id': '3.774',
    'parent': '2.78',
    'name': '协泰中心'
}, {
    'value': 2,
    'id': '3.775',
    'parent': '2.78',
    'name': '嘉麒大厦'
}, {
    'value': 13,
    'id': '3.776',
    'parent': '2.78',
    'name': '国家会展中心'
}, {
    'value': 3,
    'id': '3.777',
    'parent': '2.78',
    'name': '尚嘉中心'
}, {
    'value': 1,
    'id': '3.778',
    'parent': '2.78',
    'name': '广顺商务中心'
}, {
    'value': 5,
    'id': '3.779',
    'parent': '2.78',
    'name': '新虹桥中心大厦'
}, {
    'value': 1,
    'id': '3.780',
    'parent': '2.78',
    'name': '海盈商务中心'
}, {
    'value': 1,
    'id': '3.781',
    'parent': '2.78',
    'name': '现代广场'
}, {
    'value': 1,
    'id': '3.782',
    'parent': '2.78',
    'name': '申虹国际大厦'
}, {
    'value': 5,
    'id': '3.783',
    'parent': '2.78',
    'name': '盛高国际'
}, {
    'value': 1,
    'id': '3.784',
    'parent': '2.78',
    'name': '虹桥上海城'
}, {
    'value': 10,
    'id': '3.785',
    'parent': '2.78',
    'name': '虹桥天地'
}, {
    'value': 6,
    'id': '3.786',
    'parent': '2.78',
    'name': '虹桥银城大厦'
}, {
    'value': 5,
    'id': '3.787',
    'parent': '2.78',
    'name': '远东国际广场'
}, {
    'value': 2,
    'id': '3.788',
    'parent': '2.78',
    'name': '金桥大厦'
}, {
    'value': 3,
    'id': '3.789',
    'parent': '2.78',
    'name': '金虹桥国际中心'
}, {
    'value': 6,
    'id': '3.790',
    'parent': '2.78',
    'name': '鑫达大厦'
}, {
    'value': 1,
    'id': '3.791',
    'parent': '2.78',
    'name': '锦明大厦'
}, {
    'value': 8,
    'id': '3.792',
    'parent': '2.79',
    'name': '七宝宝龙城'
}, {
    'value': 6,
    'id': '3.793',
    'parent': '2.79',
    'name': '七宝宝龙城市广场'
}, {
    'value': 1,
    'id': '3.794',
    'parent': '2.79',
    'name': '七宝易园'
}, {
    'value': 1,
    'id': '3.795',
    'parent': '2.79',
    'name': '七莘红点城'
}, {
    'value': 14,
    'id': '3.796',
    'parent': '2.79',
    'name': '万科七宝国际'
}, {
    'value': 6,
    'id': '3.797',
    'parent': '2.79',
    'name': '丰树商业城'
}, {
    'value': 5,
    'id': '3.798',
    'parent': '2.79',
    'name': '华商时代广场'
}, {
    'value': 5,
    'id': '3.799',
    'parent': '2.79',
    'name': '台尚创意园'
}, {
    'value': 2,
    'id': '3.800',
    'parent': '2.79',
    'name': '宝虹中心'
}, {
    'value': 1,
    'id': '3.801',
    'parent': '2.79',
    'name': '德必易园'
}, {
    'value': 3,
    'id': '3.802',
    'parent': '2.79',
    'name': '明谷科技园'
}, {
    'value': 1,
    'id': '3.803',
    'parent': '2.79',
    'name': '祥鹿大厦'
}, {
    'value': 1,
    'id': '3.804',
    'parent': '2.79',
    'name': '福克斯(银座)旗舰商务区'
}, {
    'value': 1,
    'id': '3.805',
    'parent': '2.79',
    'name': '福克斯（银石）商务中心'
}, {
    'value': 1,
    'id': '3.806',
    'parent': '2.79',
    'name': '虹桥机场商务楼'
}, {
    'value': 5,
    'id': '3.807',
    'parent': '2.79',
    'name': '财富108广场'
}, {
    'value': 1,
    'id': '3.808',
    'parent': '2.79',
    'name': '银石科技园'
}, {
    'value': 2,
    'id': '3.809',
    'parent': '2.79',
    'name': '闵欣大厦'
}, {
    'value': 1,
    'id': '3.810',
    'parent': '2.79',
    'name': '麦可将园区'
}, {
    'value': 13,
    'id': '3.811',
    'parent': '2.80',
    'name': '万科时一区'
}, {
    'value': 5,
    'id': '3.812',
    'parent': '2.80',
    'name': '万通中心'
}, {
    'value': 5,
    'id': '3.813',
    'parent': '2.80',
    'name': '中骏广场'
}, {
    'value': 1,
    'id': '3.814',
    'parent': '2.80',
    'name': '光宝科技大厦'
}, {
    'value': 2,
    'id': '3.815',
    'parent': '2.80',
    'name': '冠捷科技大楼'
}, {
    'value': 2,
    'id': '3.816',
    'parent': '2.80',
    'name': '恒基•旭辉中心'
}, {
    'value': 9,
    'id': '3.817',
    'parent': '2.80',
    'name': '虹桥万科中心'
}, {
    'value': 7,
    'id': '3.818',
    'parent': '2.80',
    'name': '虹桥丽宝广场'
}, {
    'value': 6,
    'id': '3.819',
    'parent': '2.80',
    'name': '虹桥协信中心'
}, {
    'value': 2,
    'id': '3.820',
    'parent': '2.80',
    'name': '虹桥富力中心'
}, {
    'value': 5,
    'id': '3.821',
    'parent': '2.80',
    'name': '虹桥新地中心'
}, {
    'value': 6,
    'id': '3.822',
    'parent': '2.80',
    'name': '虹桥正荣中心'
}, {
    'value': 2,
    'id': '3.823',
    'parent': '2.80',
    'name': '虹桥汇'
}, {
    'value': 15,
    'id': '3.824',
    'parent': '2.80',
    'name': '虹桥绿谷'
}, {
    'value': 4,
    'id': '3.825',
    'parent': '2.80',
    'name': '阿里中心'
}, {
    'value': 22,
    'id': '3.826',
    'parent': '2.80',
    'name': '龙湖虹桥天街'
}, {
    'value': 13,
    'id': '3.827',
    'parent': '2.81',
    'name': '城开中心'
}, {
    'value': 1,
    'id': '3.828',
    'parent': '2.81',
    'name': '莲花国际商务广场'
}, {
    'value': 1,
    'id': '3.829',
    'parent': '2.81',
    'name': '高优商务中心'
}, {
    'value': 1,
    'id': '3.830',
    'parent': '2.82',
    'name': '上海晶碧产业园'
}, {
    'value': 1,
    'id': '3.831',
    'parent': '2.82',
    'name': '上海电子物联产业园'
}, {
    'value': 1,
    'id': '3.832',
    'parent': '2.82',
    'name': '上海陇盛科技大楼'
}, {
    'value': 4,
    'id': '3.833',
    'parent': '2.82',
    'name': '宁谷商务大厦'
}, {
    'value': 1,
    'id': '3.834',
    'parent': '2.82',
    'name': '紫竹科学园区'
}, {
    'value': 2,
    'id': '3.835',
    'parent': '2.82',
    'name': '绿亮虹梅南路科创园'
}, {
    'value': 4,
    'id': '3.836',
    'parent': '2.82',
    'name': '莲谷产业园'
}, {
    'value': 1,
    'id': '3.837',
    'parent': '2.83',
    'name': '863基地'
}, {
    'value': 2,
    'id': '3.838',
    'parent': '2.83',
    'name': '万科VMO'
}, {
    'value': 1,
    'id': '3.839',
    'parent': '2.83',
    'name': '上海节能环保科技企业孵化基地'
}, {
    'value': 1,
    'id': '3.840',
    'parent': '2.83',
    'name': '复地浦江中心二期'
}, {
    'value': 1,
    'id': '3.841',
    'parent': '2.83',
    'name': '奇亚特能源中心'
}, {
    'value': 1,
    'id': '3.842',
    'parent': '2.83',
    'name': '孵源节能环保科技企业孵化基地'
}, {
    'value': 1,
    'id': '3.843',
    'parent': '2.83',
    'name': '寰启商务园'
}, {
    'value': 4,
    'id': '3.844',
    'parent': '2.83',
    'name': '浦江智谷商务园'
}, {
    'value': 4,
    'id': '3.845',
    'parent': '2.83',
    'name': '浦江知地'
}, {
    'value': 5,
    'id': '3.846',
    'parent': '2.83',
    'name': '浦江高科技园'
}, {
    'value': 2,
    'id': '3.847',
    'parent': '2.83',
    'name': '漕河泾浦江科技广场'
}, {
    'value': 2,
    'id': '3.848',
    'parent': '2.83',
    'name': '爱登堡科技园'
}, {
    'value': 2,
    'id': '3.849',
    'parent': '2.83',
    'name': '禾谷文创园'
}, {
    'value': 1,
    'id': '3.850',
    'parent': '2.83',
    'name': '红星国际广场'
}, {
    'value': 1,
    'id': '3.851',
    'parent': '2.83',
    'name': '茸锦科技园'
}, {
    'value': 2,
    'id': '3.852',
    'parent': '2.83',
    'name': '蕾特商务中心'
}, {
    'value': 1,
    'id': '3.853',
    'parent': '2.83',
    'name': '道•创空间'
}, {
    'value': 2,
    'id': '3.854',
    'parent': '2.84',
    'name': 'IF如果文化创意产业园'
}, {
    'value': 3,
    'id': '3.855',
    'parent': '2.84',
    'name': '七星创业园'
}, {
    'value': 1,
    'id': '3.856',
    'parent': '2.84',
    'name': '世宏金源中心'
}, {
    'value': 1,
    'id': '3.857',
    'parent': '2.84',
    'name': '东苑丽宝广场'
}, {
    'value': 1,
    'id': '3.858',
    'parent': '2.84',
    'name': '中展大厦'
}, {
    'value': 4,
    'id': '3.859',
    'parent': '2.84',
    'name': '中铁诺德国际中心'
}, {
    'value': 4,
    'id': '3.860',
    'parent': '2.84',
    'name': '凯德龙之梦'
}, {
    'value': 3,
    'id': '3.861',
    'parent': '2.84',
    'name': '凯德龙之梦闵行广场'
}, {
    'value': 2,
    'id': '3.862',
    'parent': '2.84',
    'name': '大虹桥国际中心'
}, {
    'value': 3,
    'id': '3.863',
    'parent': '2.84',
    'name': '强劲大厦'
}, {
    'value': 1,
    'id': '3.864',
    'parent': '2.84',
    'name': '福克斯元江路创新园'
}, {
    'value': 6,
    'id': '3.865',
    'parent': '2.84',
    'name': '绿地蓝海'
}, {
    'value': 1,
    'id': '3.866',
    'parent': '2.84',
    'name': '绿地蓝海大厦3号楼'
}, {
    'value': 2,
    'id': '3.867',
    'parent': '2.84',
    'name': '莘东置业大厦'
}, {
    'value': 1,
    'id': '3.868',
    'parent': '2.84',
    'name': '莘吴之星'
}, {
    'value': 1,
    'id': '3.869',
    'parent': '2.84',
    'name': '莘庄产学研基地'
}, {
    'value': 3,
    'id': '3.870',
    'parent': '2.84',
    'name': '西子国际中心'
}, {
    'value': 2,
    'id': '3.871',
    'parent': '2.84',
    'name': '解放日报大厦（闵行）'
}, {
    'value': 4,
    'id': '3.872',
    'parent': '2.84',
    'name': '赢嘉广场'
}, {
    'value': 1,
    'id': '3.873',
    'parent': '2.85',
    'name': '富力虹桥十号'
}, {
    'value': 1,
    'id': '3.874',
    'parent': '2.85',
    'name': '灿虹精英大厦'
}, {
    'value': 1,
    'id': '3.875',
    'parent': '2.85',
    'name': '燎申国际大厦'
}, {
    'value': 6,
    'id': '3.876',
    'parent': '2.85',
    'name': '虹桥德必易园'
}, {
    'value': 1,
    'id': '3.877',
    'parent': '2.85',
    'name': '虹欣大厦'
}, {
    'value': 2,
    'id': '3.878',
    'parent': '2.86',
    'name': '上海金领谷科技产业园'
}, {
    'value': 1,
    'id': '3.879',
    'parent': '2.86',
    'name': '博济F-1088(放鹤路)'
}, {
    'value': 1,
    'id': '3.880',
    'parent': '2.86',
    'name': '山谷you帮大厦'
}, {
    'value': 1,
    'id': '3.881',
    'parent': '2.86',
    'name': '歆翱智慧谷'
}, {
    'value': 2,
    'id': '3.882',
    'parent': '2.87',
    'name': '万象城'
}, {
    'value': 1,
    'id': '3.883',
    'parent': '2.87',
    'name': '宝纳大厦'
}, {
    'value': 1,
    'id': '3.884',
    'parent': '2.87',
    'name': '富群商务大厦A栋'
}, {
    'value': 3,
    'id': '3.885',
    'parent': '2.87',
    'name': '帝宝国际大厦'
}, {
    'value': 1,
    'id': '3.886',
    'parent': '2.87',
    'name': '灿虹大厦'
}, {
    'value': 1,
    'id': '3.887',
    'parent': '2.87',
    'name': '莱茵·虹桥中心'
}, {
    'value': 2,
    'id': '3.888',
    'parent': '2.87',
    'name': '莱茵•虹景中心'
}, {
    'value': 1,
    'id': '3.889',
    'parent': '2.87',
    'name': '虹桥525创意园'
}, {
    'value': 1,
    'id': '3.890',
    'parent': '2.87',
    'name': '虹桥总部1号'
}, {
    'value': 1,
    'id': '3.891',
    'parent': '2.87',
    'name': '虹桥晶座'
}, {
    'value': 2,
    'id': '3.892',
    'parent': '2.87',
    'name': '金汇德必易园'
}, {
    'value': 1,
    'id': '3.893',
    'parent': '2.87',
    'name': '银洲国际商务大厦'
}, {
    'value': 8,
    'id': '3.894',
    'parent': '2.88',
    'name': '东方环球企业中心'
}, {
    'value': 5,
    'id': '3.895',
    'parent': '2.88',
    'name': '中环协信天地'
}, {
    'value': 2,
    'id': '3.896',
    'parent': '2.88',
    'name': '中融信托大厦'
}, {
    'value': 11,
    'id': '3.897',
    'parent': '2.88',
    'name': '中铁中环时代广场'
}, {
    'value': 1,
    'id': '3.898',
    'parent': '2.88',
    'name': '和典创意园'
}, {
    'value': 3,
    'id': '3.899',
    'parent': '2.88',
    'name': '和源企业广场'
}, {
    'value': 1,
    'id': '3.900',
    'parent': '2.88',
    'name': '大宁国际商业广场'
}, {
    'value': 1,
    'id': '3.901',
    'parent': '2.88',
    'name': '大宁易园'
}, {
    'value': 1,
    'id': '3.902',
    'parent': '2.88',
    'name': '大宁财智中心'
}, {
    'value': 2,
    'id': '3.903',
    'parent': '2.88',
    'name': '宝华中心'
}, {
    'value': 1,
    'id': '3.904',
    'parent': '2.88',
    'name': '海棠大厦'
}, {
    'value': 3,
    'id': '3.905',
    'parent': '2.88',
    'name': '珠江创意中心'
}, {
    'value': 7,
    'id': '3.906',
    'parent': '2.88',
    'name': '金谷中环大厦'
}, {
    'value': 3,
    'id': '3.907',
    'parent': '2.88',
    'name': '金赢108创意广场'
}, {
    'value': 1,
    'id': '3.908',
    'parent': '2.88',
    'name': '静安东贤大厦'
}, {
    'value': 1,
    'id': '3.909',
    'parent': '2.88',
    'name': '静安新业坊'
}, {
    'value': 1,
    'id': '3.910',
    'parent': '2.89',
    'name': '中环企业广场'
}, {
    'value': 1,
    'id': '3.911',
    'parent': '2.89',
    'name': '中环永新国际广场'
}, {
    'value': 2,
    'id': '3.912',
    'parent': '2.89',
    'name': '久合科技园'
}, {
    'value': 1,
    'id': '3.913',
    'parent': '2.89',
    'name': '共和国际商务广场'
}, {
    'value': 2,
    'id': '3.914',
    'parent': '2.89',
    'name': '大宁中心广场'
}, {
    'value': 5,
    'id': '3.915',
    'parent': '2.89',
    'name': '大宁音乐广场'
}, {
    'value': 1,
    'id': '3.916',
    'parent': '2.89',
    'name': '宝华国际广场'
}, {
    'value': 2,
    'id': '3.917',
    'parent': '2.89',
    'name': '祥腾财富广场'
}, {
    'value': 1,
    'id': '3.918',
    'parent': '2.89',
    'name': '诺诚1895创意园'
}, {
    'value': 2,
    'id': '3.919',
    'parent': '2.89',
    'name': '雍和创智广场'
}, {
    'value': 1,
    'id': '3.920',
    'parent': '2.89',
    'name': '飞乐企业大厦'
}, {
    'value': 4,
    'id': '3.921',
    'parent': '2.89',
    'name': '飞马旅5iCENTER创意园'
}, {
    'value': 2,
    'id': '3.922',
    'parent': '2.90',
    'name': '一天下大厦'
}, {
    'value': 4,
    'id': '3.923',
    'parent': '2.90',
    'name': '上海现代交通商务大厦'
}, {
    'value': 9,
    'id': '3.924',
    'parent': '2.90',
    'name': '中海万锦城'
}, {
    'value': 3,
    'id': '3.925',
    'parent': '2.90',
    'name': '企业广场'
}, {
    'value': 2,
    'id': '3.926',
    'parent': '2.90',
    'name': '凯德星贸中心'
}, {
    'value': 2,
    'id': '3.927',
    'parent': '2.90',
    'name': '凯旋门大厦'
}, {
    'value': 1,
    'id': '3.928',
    'parent': '2.90',
    'name': '华瑞大厦'
}, {
    'value': 1,
    'id': '3.929',
    'parent': '2.90',
    'name': '华舟大厦'
}, {
    'value': 1,
    'id': '3.930',
    'parent': '2.90',
    'name': '和源大楼'
}, {
    'value': 8,
    'id': '3.931',
    'parent': '2.90',
    'name': '嘉里不夜城'
}, {
    'value': 2,
    'id': '3.932',
    'parent': '2.90',
    'name': '宝矿洲际商务中心'
}, {
    'value': 1,
    'id': '3.933',
    'parent': '2.90',
    'name': '康吉大厦'
}, {
    'value': 3,
    'id': '3.934',
    'parent': '2.90',
    'name': '恒汇国际大厦'
}, {
    'value': 1,
    'id': '3.935',
    'parent': '2.90',
    'name': '新华文化科技园'
}, {
    'value': 1,
    'id': '3.936',
    'parent': '2.90',
    'name': '新发展大厦'
}, {
    'value': 4,
    'id': '3.937',
    'parent': '2.90',
    'name': '新理想大厦'
}, {
    'value': 1,
    'id': '3.938',
    'parent': '2.90',
    'name': '机电大厦'
}, {
    'value': 5,
    'id': '3.939',
    'parent': '2.90',
    'name': '洲际中心'
}, {
    'value': 4,
    'id': '3.940',
    'parent': '2.90',
    'name': '苏河1号'
}, {
    'value': 2,
    'id': '3.941',
    'parent': '2.90',
    'name': '达人湾创智广场'
}, {
    'value': 1,
    'id': '3.942',
    'parent': '2.90',
    'name': '达邦协作广场'
}, {
    'value': 1,
    'id': '3.943',
    'parent': '2.90',
    'name': '金城大厦'
}, {
    'value': 2,
    'id': '3.944',
    'parent': '2.90',
    'name': '铭德国际广场'
}, {
    'value': 1,
    'id': '3.945',
    'parent': '2.90',
    'name': '银历大厦'
}, {
    'value': 5,
    'id': '3.946',
    'parent': '2.90',
    'name': '长泰企业天地'
}, {
    'value': 5,
    'id': '3.947',
    'parent': '2.91',
    'name': '绿地中央广场'
}, {
    'value': 1,
    'id': '3.948',
    'parent': '2.91',
    'name': '通用大厦'
}, {
    'value': 5,
    'id': '3.949',
    'parent': '2.92',
    'name': 'e通世界'
}, {
    'value': 2,
    'id': '3.950',
    'parent': '2.92',
    'name': 'e通世界商务园五区'
}, {
    'value': 5,
    'id': '3.951',
    'parent': '2.92',
    'name': '虹桥世界中心'
}, {
    'value': 1,
    'id': '3.952',
    'parent': '2.93',
    'name': '555大厦'
}, {
    'value': 1,
    'id': '3.953',
    'parent': '2.93',
    'name': '688广场'
}, {
    'value': 11,
    'id': '3.954',
    'parent': '2.93',
    'name': 'SOHO东海广场'
}, {
    'value': 2,
    'id': '3.955',
    'parent': '2.93',
    'name': '上海商城'
}, {
    'value': 4,
    'id': '3.956',
    'parent': '2.93',
    'name': '上海大中里'
}, {
    'value': 2,
    'id': '3.957',
    'parent': '2.93',
    'name': '上海展览中心'
}, {
    'value': 5,
    'id': '3.958',
    'parent': '2.93',
    'name': '上海招商局广场'
}, {
    'value': 3,
    'id': '3.959',
    'parent': '2.93',
    'name': '东方众鑫大厦'
}, {
    'value': 4,
    'id': '3.960',
    'parent': '2.93',
    'name': '东方海外大厦'
}, {
    'value': 5,
    'id': '3.961',
    'parent': '2.93',
    'name': '中创大厦'
}, {
    'value': 2,
    'id': '3.962',
    'parent': '2.93',
    'name': '丽都新贵'
}, {
    'value': 1,
    'id': '3.963',
    'parent': '2.93',
    'name': '云海苑'
}, {
    'value': 2,
    'id': '3.964',
    'parent': '2.93',
    'name': '仲益大厦'
}, {
    'value': 12,
    'id': '3.965',
    'parent': '2.93',
    'name': '会德丰国际广场'
}, {
    'value': 1,
    'id': '3.966',
    'parent': '2.93',
    'name': '兴业大厦'
}, {
    'value': 14,
    'id': '3.967',
    'parent': '2.93',
    'name': '南证大厦'
}, {
    'value': 3,
    'id': '3.968',
    'parent': '2.93',
    'name': '嘉地中心'
}, {
    'value': 16,
    'id': '3.969',
    'parent': '2.93',
    'name': '嘉里中心'
}, {
    'value': 1,
    'id': '3.970',
    'parent': '2.93',
    'name': '国立大厦'
}, {
    'value': 1,
    'id': '3.971',
    'parent': '2.93',
    'name': '广电大厦'
}, {
    'value': 1,
    'id': '3.972',
    'parent': '2.93',
    'name': '恒利国际大厦'
}, {
    'value': 1,
    'id': '3.973',
    'parent': '2.93',
    'name': '文新报业大厦'
}, {
    'value': 2,
    'id': '3.974',
    'parent': '2.93',
    'name': '旺旺大厦'
}, {
    'value': 3,
    'id': '3.975',
    'parent': '2.93',
    'name': '晶采世纪大厦'
}, {
    'value': 3,
    'id': '3.976',
    'parent': '2.93',
    'name': '梅龙镇广场'
}, {
    'value': 1,
    'id': '3.977',
    'parent': '2.93',
    'name': '汇银大厦'
}, {
    'value': 5,
    'id': '3.978',
    'parent': '2.93',
    'name': '科恩国际中心'
}, {
    'value': 2,
    'id': '3.979',
    'parent': '2.93',
    'name': '紫安大厦'
}, {
    'value': 1,
    'id': '3.980',
    'parent': '2.93',
    'name': '金鹰国际广场'
}, {
    'value': 2,
    'id': '3.981',
    'parent': '2.93',
    'name': '铜仁88'
}, {
    'value': 3,
    'id': '3.982',
    'parent': '2.93',
    'name': '锦江向阳大楼'
}, {
    'value': 2,
    'id': '3.983',
    'parent': '2.93',
    'name': '长春藤运通大厦'
}, {
    'value': 2,
    'id': '3.984',
    'parent': '2.93',
    'name': '静安新时代大厦'
}, {
    'value': 5,
    'id': '3.985',
    'parent': '2.93',
    'name': '静安高和大厦'
}, {
    'value': 1,
    'id': '3.986',
    'parent': '2.94',
    'name': '万源创意园'
}, {
    'value': 1,
    'id': '3.987',
    'parent': '2.94',
    'name': '三和大厦'
}, {
    'value': 1,
    'id': '3.988',
    'parent': '2.94',
    'name': '开开大厦'
}, {
    'value': 1,
    'id': '3.989',
    'parent': '2.94',
    'name': '汇智创意园'
}, {
    'value': 3,
    'id': '3.990',
    'parent': '2.94',
    'name': '海森国际大厦'
}, {
    'value': 1,
    'id': '3.991',
    'parent': '2.94',
    'name': '百乐门商务楼'
}, {
    'value': 2,
    'id': '3.992',
    'parent': '2.94',
    'name': '金峰世纪大厦'
}, {
    'value': 2,
    'id': '3.993',
    'parent': '2.95',
    'name': '同乐坊'
}, {
    'value': 6,
    'id': '3.994',
    'parent': '2.95',
    'name': '和一大厦'
}, {
    'value': 1,
    'id': '3.995',
    'parent': '2.95',
    'name': '圣天地商务大厦'
}, {
    'value': 1,
    'id': '3.996',
    'parent': '2.95',
    'name': '富容大厦'
}, {
    'value': 1,
    'id': '3.997',
    'parent': '2.95',
    'name': '德安大厦'
}, {
    'value': 1,
    'id': '3.998',
    'parent': '2.95',
    'name': '新越时美大厦'
}, {
    'value': 2,
    'id': '3.999',
    'parent': '2.95',
    'name': '柴安大厦'
}, {
    'value': 1,
    'id': '3.1000',
    'parent': '2.95',
    'name': '申银发展大厦'
}, {
    'value': 4,
    'id': '3.1001',
    'parent': '2.95',
    'name': '石油天然气大厦'
}, {
    'value': 6,
    'id': '3.1002',
    'parent': '2.95',
    'name': '静安创展中心'
}, {
    'value': 1,
    'id': '3.1003',
    'parent': '2.95',
    'name': '静安创想中心'
}, {
    'value': 1,
    'id': '3.1004',
    'parent': '2.95',
    'name': '静安现代产业大厦'
}, {
    'value': 9,
    'id': '3.1005',
    'parent': '2.96',
    'name': '1788国际中心'
}, {
    'value': 2,
    'id': '3.1006',
    'parent': '2.96',
    'name': '800秀创意园区'
}, {
    'value': 2,
    'id': '3.1007',
    'parent': '2.96',
    'name': 'WE国际文化创意中心（静安）'
}, {
    'value': 3,
    'id': '3.1008',
    'parent': '2.96',
    'name': '上海阿波罗大厦'
}, {
    'value': 3,
    'id': '3.1009',
    'parent': '2.96',
    'name': '世纪时空'
}, {
    'value': 11,
    'id': '3.1010',
    'parent': '2.96',
    'name': '中信泰富广场'
}, {
    'value': 1,
    'id': '3.1011',
    'parent': '2.96',
    'name': '城市机场航站楼'
}, {
    'value': 3,
    'id': '3.1012',
    'parent': '2.96',
    'name': '巨富大厦'
}, {
    'value': 8,
    'id': '3.1013',
    'parent': '2.96',
    'name': '恒隆广场'
}, {
    'value': 2,
    'id': '3.1014',
    'parent': '2.96',
    'name': '愚园108'
}, {
    'value': 2,
    'id': '3.1015',
    'parent': '2.96',
    'name': '环球世界大厦'
}, {
    'value': 1,
    'id': '3.1016',
    'parent': '2.96',
    'name': '百乐门大都会'
}, {
    'value': 2,
    'id': '3.1017',
    'parent': '2.96',
    'name': '越洋广场'
}, {
    'value': 2,
    'id': '3.1018',
    'parent': '2.96',
    'name': '金航大厦'
}, {
    'value': 11,
    'id': '3.1019',
    'parent': '2.96',
    'name': '金融街静安中心'
}, {
    'value': 1,
    'id': '3.1020',
    'parent': '2.96',
    'name': '阳光科技大厦'
}, {
    'value': 7,
    'id': '3.1021',
    'parent': '2.96',
    'name': '静安中华大厦'
}, {
    'value': 2,
    'id': '3.1022',
    'parent': '2.96',
    'name': '静安晶品中心'
}, {
    'value': 2,
    'id': '3.1023',
    'parent': '2.96',
    'name': '静安设计中心'
}, {
    'value': 3,
    'id': '3.1024',
    'parent': '2.97',
    'name': '世界贸易大厦'
}, {
    'value': 6,
    'id': '3.1025',
    'parent': '2.97',
    'name': '世贸大厦'
}, {
    'value': 1,
    'id': '3.1026',
    'parent': '2.97',
    'name': '东方有线大厦'
}, {
    'value': 1,
    'id': '3.1027',
    'parent': '2.97',
    'name': '东海商业中心二期'
}, {
    'value': 4,
    'id': '3.1028',
    'parent': '2.97',
    'name': '中区广场'
}, {
    'value': 4,
    'id': '3.1029',
    'parent': '2.97',
    'name': '中国民生银行大厦'
}, {
    'value': 2,
    'id': '3.1030',
    'parent': '2.97',
    'name': '中海国际中心'
}, {
    'value': 2,
    'id': '3.1031',
    'parent': '2.97',
    'name': '亚洲大厦'
}, {
    'value': 5,
    'id': '3.1032',
    'parent': '2.97',
    'name': '仙乐斯广场'
}, {
    'value': 1,
    'id': '3.1033',
    'parent': '2.97',
    'name': '六合大厦'
}, {
    'value': 6,
    'id': '3.1034',
    'parent': '2.97',
    'name': '华旭国际大厦'
}, {
    'value': 1,
    'id': '3.1035',
    'parent': '2.97',
    'name': '南苏州路独栋'
}, {
    'value': 4,
    'id': '3.1036',
    'parent': '2.97',
    'name': '天安中心'
}, {
    'value': 9,
    'id': '3.1037',
    'parent': '2.97',
    'name': '峻岭广场'
}, {
    'value': 1,
    'id': '3.1038',
    'parent': '2.97',
    'name': '工商联大厦'
}, {
    'value': 3,
    'id': '3.1039',
    'parent': '2.97',
    'name': '廖创兴金融中心'
}, {
    'value': 4,
    'id': '3.1040',
    'parent': '2.97',
    'name': '恒积大厦'
}, {
    'value': 4,
    'id': '3.1041',
    'parent': '2.97',
    'name': '来福士广场'
}, {
    'value': 6,
    'id': '3.1042',
    'parent': '2.97',
    'name': '海洋大厦'
}, {
    'value': 5,
    'id': '3.1043',
    'parent': '2.97',
    'name': '海通证券大厦'
}, {
    'value': 1,
    'id': '3.1044',
    'parent': '2.97',
    'name': '淮云大厦'
}, {
    'value': 4,
    'id': '3.1045',
    'parent': '2.97',
    'name': '淮海中华大厦'
}, {
    'value': 9,
    'id': '3.1046',
    'parent': '2.97',
    'name': '港泰广场'
}, {
    'value': 3,
    'id': '3.1047',
    'parent': '2.97',
    'name': '港陆广场'
}, {
    'value': 1,
    'id': '3.1048',
    'parent': '2.97',
    'name': '港陆黄浦中心'
}, {
    'value': 2,
    'id': '3.1049',
    'parent': '2.97',
    'name': '都市总部大楼'
}, {
    'value': 2,
    'id': '3.1050',
    'parent': '2.97',
    'name': '金陵海欣大厦'
}, {
    'value': 3,
    'id': '3.1051',
    'parent': '2.97',
    'name': '长江新能源大厦'
}, {
    'value': 6,
    'id': '3.1052',
    'parent': '2.97',
    'name': '雅居乐国际广场'
}, {
    'value': 1,
    'id': '3.1053',
    'parent': '2.97',
    'name': '鸿祥大厦'
}, {
    'value': 6,
    'id': '3.1054',
    'parent': '2.98',
    'name': '上海科技京城'
}, {
    'value': 2,
    'id': '3.1055',
    'parent': '2.98',
    'name': '东吴证券大厦'
}, {
    'value': 6,
    'id': '3.1056',
    'parent': '2.98',
    'name': '中外运大厦'
}, {
    'value': 1,
    'id': '3.1057',
    'parent': '2.98',
    'name': '久事商务大厦'
}, {
    'value': 2,
    'id': '3.1058',
    'parent': '2.98',
    'name': '亚龙国际广场'
}, {
    'value': 4,
    'id': '3.1059',
    'parent': '2.98',
    'name': '华盛大厦'
}, {
    'value': 1,
    'id': '3.1060',
    'parent': '2.98',
    'name': '名人商业大厦'
}, {
    'value': 2,
    'id': '3.1061',
    'parent': '2.98',
    'name': '外滩德必WE'
}, {
    'value': 1,
    'id': '3.1062',
    'parent': '2.98',
    'name': '恒基大厦'
}, {
    'value': 2,
    'id': '3.1063',
    'parent': '2.98',
    'name': '明天广场'
}, {
    'value': 1,
    'id': '3.1064',
    'parent': '2.98',
    'name': '春申江大厦'
}, {
    'value': 1,
    'id': '3.1065',
    'parent': '2.98',
    'name': '申华金融大厦'
}, {
    'value': 1,
    'id': '3.1066',
    'parent': '2.98',
    'name': '申大厦'
}, {
    'value': 1,
    'id': '3.1067',
    'parent': '2.98',
    'name': '越洋国际广场'
}, {
    'value': 4,
    'id': '3.1068',
    'parent': '2.98',
    'name': '金光外滩中心'
}, {
    'value': 3,
    'id': '3.1069',
    'parent': '2.98',
    'name': '金融广场'
}, {
    'value': 10,
    'id': '3.1070',
    'parent': '2.99',
    'name': '旺角广场'
}, {
    'value': 1,
    'id': '3.1071',
    'parent': '2.99',
    'name': '朝阳门大厦'
}, {
    'value': 1,
    'id': '3.1072',
    'parent': '2.100',
    'name': '光明大厦'
}, {
    'value': 4,
    'id': '3.1073',
    'parent': '2.100',
    'name': '创邑socool创意园'
}, {
    'value': 1,
    'id': '3.1074',
    'parent': '2.100',
    'name': '华普科技大厦'
}, {
    'value': 3,
    'id': '3.1075',
    'parent': '2.100',
    'name': '华隆大厦'
}, {
    'value': 1,
    'id': '3.1076',
    'parent': '2.100',
    'name': '外滩8号'
}, {
    'value': 14,
    'id': '3.1077',
    'parent': '2.100',
    'name': '外滩SOHO'
}, {
    'value': 12,
    'id': '3.1078',
    'parent': '2.100',
    'name': '外滩金融中心'
}, {
    'value': 2,
    'id': '3.1079',
    'parent': '2.100',
    'name': '洛克外滩源'
}, {
    'value': 3,
    'id': '3.1080',
    'parent': '2.100',
    'name': '物资大厦'
}, {
    'value': 1,
    'id': '3.1081',
    'parent': '2.100',
    'name': '老码头创意园'
}, {
    'value': 1,
    'id': '3.1082',
    'parent': '2.100',
    'name': '腾飞浦汇大厦'
}, {
    'value': 1,
    'id': '3.1083',
    'parent': '2.100',
    'name': '金延大楼'
}, {
    'value': 4,
    'id': '3.1084',
    'parent': '2.100',
    'name': '高登金融大厦'
}, {
    'value': 3,
    'id': '3.1085',
    'parent': '2.101',
    'name': '万事利大厦'
}, {
    'value': 1,
    'id': '3.1086',
    'parent': '2.101',
    'name': '京德大楼'
}, {
    'value': 2,
    'id': '3.1087',
    'parent': '2.101',
    'name': '南开大厦'
}, {
    'value': 3,
    'id': '3.1088',
    'parent': '2.101',
    'name': '安基大厦'
}, {
    'value': 1,
    'id': '3.1089',
    'parent': '2.101',
    'name': '康宁大厦'
}, {
    'value': 2,
    'id': '3.1090',
    'parent': '2.101',
    'name': '惠德大厦'
}, {
    'value': 1,
    'id': '3.1091',
    'parent': '2.101',
    'name': '新上海城市广场'
}, {
    'value': 1,
    'id': '3.1092',
    'parent': '2.101',
    'name': '新华联大厦'
}, {
    'value': 1,
    'id': '3.1093',
    'parent': '2.101',
    'name': '永惠大厦写字楼'
}, {
    'value': 2,
    'id': '3.1094',
    'parent': '2.101',
    'name': '金天地国际大厦'
}, {
    'value': 1,
    'id': '3.1095',
    'parent': '2.102',
    'name': '香港名都写字楼'
}]
